### PR TITLE
feat: add catalog/schema subcommands to flight_sql_client.

### LINKED ISSUE #6331: Add Catalog DB Schema subcommands to `flight_sql_client`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

When using the `flight_sql_client` it can be helpful to interrogate the Flight SQL server for information about available catalogs, db schemas and tables. 

**Describe the solution you'd like**
Adding subcommands to the CLI that mirror the various FlightSQL commands about catalogs, schemas and tables.

**Describe alternatives you've considered**
 We could support `SHOW ...` variant queries and map them to the FlightSQL commands, however this is likely not as portable as a direct mapping of CLI subcommand to FlightSQL command.

**Additional context**

I have PR in progress.

### PR DESCRIPTION
**Pull request by nathanielc**
# Which issue does this PR close?

Closes #6331 

# Rationale for this change
 
Adds the proposed solution from the issue.

# What changes are included in this PR?

# Are there any user-facing changes?

Yes, the new subcommands on the CLI are documented, producing good help text within the CLI.

### CODE REVIEW

**Comment by crepererum** [comment]
Implementation looks good, but I agree with @alamb that a test is required. Doesn't have to be super sophisticated though, it's mostly a smoke test to check that the wiring is sound.

**Comment by nathanielc** [comment]
@crepererum @alamb I have added tests, somehow I missed that they existed when I first looked. 

To make implementing the service I copied the builder pattern from the CommandGetDbSchemas for the CommandGetTableTypes. While its a trivial implementation it makes implementing the service simple as it follows the same pattern as the other commands.

**Comment by crepererum** [comment]
clippy still complaints (minor) issue, the overall approach/code looks good though

**Comment by nathanielc** [comment]
@crepererum Thanks I fixed the clippy issue.

**Review by crepererum — APPROVED** [review]
thank you :slightly_smiling_face:

**Pull request merged**
