### PR TITLE
Parquet: Fix string display for f32/f64 zero values

### LINKED ISSUE #5045: Parquet record api: display for float/double 0.0 shows 0E0
**Describe the bug**

Floats and doubles that are zero (or negative zero) are displayed in format `0E0` for `Field` from record api

**To Reproduce**

In unit test:
https://github.com/apache/arrow-rs/blob/91acfb07a9929a2d6721c5417e47c0c472372a86/parquet/src/record/api.rs#L1148-L1158

Modify to add new case:
```rust
    #[test]
    fn test_convert_float_to_string() {
        assert_eq!(format!("{}", Field::Float(1.0)), "1.0");
        assert_eq!(format!("{}", Field::Float(9.63)), "9.63");
        assert_eq!(format!("{}", Field::Float(1e-15)), "0.000000000000001");
        assert_eq!(format!("{}", Field::Float(1e-16)), "1E-16");
        assert_eq!(format!("{}", Field::Float(1e19)), "10000000000000000000.0");
        assert_eq!(format!("{}", Field::Float(1e20)), "1E20");
        assert_eq!(format!("{}", Field::Float(1.7976931E30)), "1.7976931E30");
        assert_eq!(format!("{}", Field::Float(-1.7976931E30)), "-1.7976931E30");
        assert_eq!(format!("{}", Field::Float(0.0)), "0.0"); // new test case, should succeed
    }
```

Running test will fail:

```sh
parquet$ cargo test --lib record::api::tests::test_convert_float_to_string -- --exact
    Finished test [unoptimized + debuginfo] target(s) in 0.06s
     Running unittests src/lib.rs (/media/jeffrey/1tb_860evo_ssd/.cargo_target_cache/debug/deps/parquet-b466af98c7f74484)

running 1 test
test record::api::tests::test_convert_float_to_string ... FAILED

failures:

---- record::api::tests::test_convert_float_to_string stdout ----
thread 'record::api::tests::test_convert_float_to_string' panicked at parquet/src/record/api.rs:1158:9:
assertion `left == right` failed
  left: "0E0"
 right: "0.0"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    record::api::tests::test_convert_float_to_string

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 616 filtered out; finished in 0.00s

error: test failed, to rerun pass `--lib`
```

**Expected behavior**

Test case succeeds

**Additional context**

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5045

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
What is the issue with 0E0? I agree it looks a little odd, but it isn't incorrect?

**Comment by Jefffrey** [comment]
> What is the issue with 0E0? I agree it looks a little odd, but it isn't incorrect?

Yeah I wasn't sure if this was intended or not. It felt like a bug since the code seemed to suggest it used the E notation for very large positive/negative numbers, and 0E0 just happened to be caught up in it accidentally.

When I was implementing f16 (https://github.com/apache/arrow-rs/pull/5003) I wasn't sure if we should display 0E0 to be consistent or just have it display 0.0 anyway

If this is behaviour is fine then can close the PR

**Comment by tustvold** [comment]
I don't have a good enough sense of what people are using the record API for to be comfortable making breaking changes to it

**Comment by Jefffrey** [comment]
No problem, closing as no need to change

**Pull request closed without merging**
