### PR TITLE
fix duration conversion error

### LINKED ISSUE #5625: write duration to parquet but read as int64
**Describe the bug**

As the title says, the `ParquetRecordBatchReader` can not recognize duration type written by pandas or polars.

**To Reproduce**

First, we should prepare parquet file
```python
import polars as pl
from datetime import timedelta

df = pl.DataFrame({
    "a":  [timedelta(days=1) for _ in range(100)]
})

df.write_parquet("./test.parquet")
```

Then, read in rust arrow-rs:
```rust
fn main() -> Result<()> {
    // Create parquet file that will be read.

    let path = "./test.parquet";
    let file = File::open(path).unwrap();

    let parquet_reader = ParquetRecordBatchReaderBuilder::try_new(file)?
        .with_batch_size(8192)
        .build()?;

    let mut batches = Vec::new();

    for batch in parquet_reader {
        batches.push(batch?);
    }

    println!("{:#?}", batches[0].schema());

    Ok(())
}
```
finally we get:
```
Schema {
    fields: [
        Field {
            name: "a",
            data_type: Int64,
            nullable: true,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {},
        },
    ],
    metadata: {},
}
```

**Expected behavior**

polars result:
```
shape: (100, 1)
┌──────────────┐
│ a            │
│ ---          │
│ duration[μs] │
╞══════════════╡
│ 1d           │
│ 1d           │
│ 1d           │
│ 1d           │
│ 1d           │
│ …            │
│ 1d           │
│ 1d           │
│ 1d           │
│ 1d           │
│ 1d           │
└──────────────┘
```
pandas result:
```
        a
0  1 days
1  1 days
2  1 days
3  1 days
4  1 days
..    ...
95 1 days
96 1 days
97 1 days
98 1 days
99 1 days

[100 rows x 1 columns]
```

**Additional context**

### PR DESCRIPTION
**Pull request by Liyixin95**
# Which issue does this PR close?

Closes #5625 

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
Could we get a test of this please

**Comment by alamb** [comment]
I agree -- a test is important to make sure we don't break this fix in some future refactor

**Comment by Liyixin95** [comment]
> Could we get a test of this please

sorry for the noob question, where should I add a test for it？

**Comment by alamb** [comment]
> > Could we get a test of this please
> 
> sorry for the noob question, where should I add a test for it？

I think we could add a round trip test here perhaps: https://github.com/apache/arrow-rs/blob/91f0b1771308609ca27db0fb1d2d49571b3980d8/parquet/src/arrow/arrow_writer/mod.rs#L1996-L2007

**Comment by Liyixin95** [comment]
> > > Could we get a test of this please
> > 
> > 
> > sorry for the noob question, where should I add a test for it？
> 
> I think we could add a round trip test here perhaps:
> 
> https://github.com/apache/arrow-rs/blob/91f0b1771308609ca27db0fb1d2d49571b3980d8/parquet/src/arrow/arrow_writer/mod.rs#L1996-L2007

write duration to parquet get a panic...
https://github.com/apache/arrow-rs/blob/a999fb86764e9310bb4822c7e7c6551f247e0e0b/parquet/src/arrow/schema/mod.rs#L445

**Comment by tustvold** [comment]
> write duration to parquet get a panic...

Yes I think we would need #1938

**Comment by alamb** [comment]
or put another way there is no way to write a duration to a parquet file with arrow-rs yet (but polars can do so).

So the ideal solution is support writing duration to parquet too (but I suspect there might be work to sort out what the desired behavior is)

Perhaps for this PR we can just check in a small parquet file that was written by polars and ensure we can read it back correctly 🤔

**Comment by tustvold** [comment]
Closing as this PR has been inactive for a while

**Comment by EddyXorb** [comment]
I have the same problem with type pl.Time. When I write a column with pl.Time to a parquet file, it reads the column as int64.

**Comment by alamb** [comment]
Thanks @EddyXorb  -- any chance you can make a PR  with a test? It seems that that is all that is missing to be able to get this fixed

**Comment by EddyXorb** [comment]
I would love to help, but at the moment I am very very busy. Once I have time (mid december), I can try to provide a test.

**Comment by alamb** [comment]
Thank you!

**Comment by sirpresto** [comment]
Hi has this been fixed? I am running into the same issue with not being able to correctly roundtrip Duration types.

**Comment by alamb** [comment]
> Hi has this been fixed? I am running into the same issue with not being able to correctly roundtrip Duration types.

I think we are waiting on a test

**Comment by Liyixin95** [comment]
@alamb I provide a test file [here](https://github.com/apache/parquet-testing/pull/80). I will add a test case in this pr after the test file get merged.

**Comment by alamb** [comment]
Ok, what is happening here is as follows: arrow-rs and arrow-cpp (and potentially polars) add a special file metadata field called "ARROW:schema" that records the desired Arrow schema. This is described in more detail here:
-  https://github.com/apache/arrow-rs/pull/7479

In order for the arrow-rs parquet reader to read the data as a duration it needs to interpret the contents of that metadata, which is what I think the code in this PR does. 

It would be really nice if the arrow-rs parquet **writer** also wrote the correct metadata so duration data in parquet that was written could be read correctly by arrow and parquet

So therefore I think we should add a test like "round trip" test that writes a RecordBatch with a Duration to a parquet file and reads it back, verifying that the read data is the same. An example of such a test is [here](https://github.com/apache/arrow-rs/blob/11c99a3232761e6d12162f6c09822de821b61c96/parquet/src/arrow/arrow_reader/mod.rs#L1383-L1415)

**Comment by tustvold** [comment]
The issue is that parquet doesn't have a duration type - see [here](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md), and the parquet schema must remain authoritative #1663.

To get around this arrow writers embed an encoded version of the arrow schema that can be used as a hint for type inference by compatible readers - see #1666.

To support writing types not supported by parquet we added a coerce_types option (see #1938). This will need to be extended to also coerce durations.

**Comment by alamb** [comment]
Let's reopen this PR as we are actively working on it now

**Comment by Liyixin95** [comment]
@alamb I fix the writer part and add a "round trip" test. Please reopen this pr and take a look.

**Comment by Liyixin95** [comment]
> For some reason GitHub will not let me reopen this PR. Can you please make a new PR and @ mention me?

Of course. Here is the [new pr](https://github.com/apache/arrow-rs/pull/7482)

**Pull request closed without merging**
