### PR TITLE
Skip RowSelectors with zero rows

### LINKED ISSUE #2669: Invalid results with `RowSelector` having `row_count` of 0
**Describe the bug**

See the discussion here https://github.com/apache/arrow-rs/pull/2656#discussion_r963722008.

In `test_fuzz_async_reader_selection` if we generate `RowSelector`s with 0 rows then we get invalid results from `ParquetRecordBatchSream`. 

**To Reproduce**

**Expected behavior**

We should handle (effectively ignore) `RowSelectors` with `row_count == 0` without issues. 

**Additional context**

### PR DESCRIPTION
**Pull request by askoa**
# Which issue does this PR close?

Closes #2669 

# Are there any user-facing changes?

no user-facing or breaking changes.

### CODE REVIEW

**Review by tustvold — COMMENTED** [review]
Could we possibly get a test of this

**Comment by askoa** [comment]
> Could we possibly get a test of this

Is it okay if I modify the test `test_fuzz_async_reader_selection` to include zero `RowSelector`s

**Comment by tustvold** [comment]
I think it would be nice to have a fully reproducible test, the fuzz tests are really there to find gaps in test coverage not to serve as it.

**Comment by askoa** [comment]
> I think it would be nice to have a fully reproducible test, the fuzz tests are really there to find gaps in test coverage not to serve as it.

I created a test borrowing heavily from the fuzz test. Let me know if it works.

**Pull request merged**
