### PR TITLE
Reduce memory usage of concat (large)utf8

### PR DESCRIPTION
**Pull request by ritchie46**
partial solution for #347 

This PR precomputes the needed length of the buffers that store the raw string data. This way we only allocate the minimal needed memory and it is faster because there will be no reallocation.

### CODE REVIEW

**Comment by alamb** [comment]
The MIRI failure is unrelated to this PR: https://github.com/apache/arrow-rs/issues/345

**Comment by Dandandan** [comment]
@ritchie46 do we have some (micro) benchmark results, like:

```cargo bench --bench concatenate_kernel -- "concat str"```

**Comment by ritchie46** [comment]
> @ritchie46 do we have some (micro) benchmark results, like:

```
Gnuplot not found, using plotters backend
concat str 10k          time:   [162.54 us 162.73 us 163.00 us]                           
                        change: [-3.7750% -3.6483% -3.5084%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe

concat str 50% nulls 10k                                                                            
                        time:   [619.71 us 621.16 us 623.28 us]
                        change: [-1.1095% -0.9350% -0.7141%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 10 outliers among 100 measurements (10.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  7 (7.00%) high severe

concat str 5% nulls 10k time:   [391.61 us 391.71 us 391.81 us]                                    
                        change: [-1.3337% -1.2446% -1.1878%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  6 (6.00%) high mild
  3 (3.00%) high severe
```

Performance wise it doesn't matter/ or hurt that much. So it mostly is more memory efficient.

**Review by Dandandan — APPROVED** [review]
LGTM thanks @ritchie46 

Great improvement / idea.
Did some tests locally with 1025 items in the array, getting a small improvement in timing there (3-5%).

**Comment by alamb** [comment]
MIRI test failure is not related to this PR (we subsequently disabled it until we can fix the errors)

**Comment by alamb** [comment]
Thanks @ritchie46

**Comment by jorgecarleitao** [comment]
I did not have the time to review this, but I think that this will over-allocate in all cases where `MutableArrayData`'s API is used.

In particular, this will overallocate in:

* `filter` arrays, as it now pre-allocates the maximum size of the string array, even if we only keep a single slot.
* `zip` kernel: we now allocate `falsy.len() + truthy.len()`, even though we will only pick either from one or the other.

**Comment by ritchie46** [comment]
I did not realize this @jorgecarleitao. What do you think about creating a builder pattern (with an prealloc option) for the concat kernel case and return the `new` implementation to the old state?

**Pull request merged**
