### PR TITLE
Add ParquetObjectReader::with_runtime (#6248)

### LINKED ISSUE #6248: Add ParquetObjectReader::with_runtime
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Tokio is a cooperative threadpool and has strong assumptions that tasks yield frequently. Running CPU-bound work on the same threadpool results in poor throughput and can lead to connections getting dropped.

**Describe the solution you'd like**

We should add a with_runtime option to ParquetObjectReader that takes a tokio handle and spawns all work to the provided runtime. This encourages decoupling CPU-bound query execution / parquet decoding, from cooperatively scheduled IO.

**Describe alternatives you've considered**

I'm aware of a number of codebases, such as InfluxDB IOx, that implement this spawning logic at the ObjectStore boundary instead.

**Additional context**

https://github.com/apache/arrow-rs/pull/4040 attempted to add something similar to object_store, but concluded this really belongs in the integrations

https://github.com/apache/arrow-rs/issues/5882 may be related to this

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #6248

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
I am depressed about the large review backlog in this crate. We are looking for more help from the community reviewing PRs -- see https://github.com/apache/arrow-rs/issues/6418 for more

**Comment by wiedld** [comment]
> Thank you @tustvold -- the idea here looks great. I think what we need to do now is to add some sort of test (maybe a doc example or something) showing how to use this and it would be good to go

@tustvold -- Mind if I take this over, adding docs & tests?

**Comment by alamb** [comment]
Converting to draft as @wiedld  works on the tests

**Comment by alamb** [comment]
Closing and @wiedld  will reopen when she has tests

**Pull request closed without merging**
