### PR TITLE
Disallow non-empty timezone for CSV reader (#3841)

### LINKED ISSUE #3841: CSV Reader Doesn't set Timezone
**Describe the bug**

Bug I noticed whilst reviewing https://github.com/apache/arrow-rs/pull/3835 and looking at what the CSV reader is doing.

In particular it collects into a `PrimitiveArray<T>` which will set the data type to be `ArrowPrimitiveType::DATA_TYPE`, which will have a timezone of `None`.

In addition it does not contain the necessary logic to correctly interpret timezones, as this was only added in https://github.com/apache/arrow-rs/pull/3795

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #3841

# Rationale for this change
 

This is a temporary "fix" for #3841 pending a more holisitic rework of the parser interface to properly support timezones #1936

Rather than silently being broken for timezones, this change makes it fail loud

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
I think there should be a test (with a reference to the ticket)

**Comment by alamb** [comment]
The only thing I think this PR needs is a test -- otherwise 👍

**Comment by alamb** [comment]
Is this PR superceded by  https://github.com/apache/arrow-rs/pull/3908 ?

**Comment by tustvold** [comment]
> Is this PR superceded by https://github.com/apache/arrow-rs/pull/3908 ?

Yes, sorry, meant to close

**Pull request closed without merging**
