### PR TITLE
Update environment variable name for amazonS3builder in integration (#2550)

### LINKED ISSUE #2550: object_store: use different AWS environment variable name in integration
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Follow-up on https://github.com/apache/arrow-rs/pull/2536#discussion_r950711802 

Using regular AWS environment variables in integration to build AmazonS3Builder can introduce confusion or clash with tests.

**Describe the solution you'd like**

Rename variable in integration (there: https://github.com/apache/arrow-rs/blob/master/.github/workflows/object_store.yml#L75) and propagate them in tests.

### PR DESCRIPTION
**Pull request by amrltqt**
# Which issue does this PR close?

Closes #2550 

# Rationale for this change

Update the environment variables names injected in the integration pipeline to test AmazonS3 client. The objective is to avoid conflicts when testing real injection while testing AmazonS3Builder::from_env() function.  

# What changes are included in this PR?

Update the github workflow pipeline + integration tests to leverage new names.

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by amrltqt** [comment]
@tustvold it seems that AWS_* are useful as an environment variable for the CI. At least to work with localstack. 

I'm starting to think that anyway we will need those variable in the CI, so we can just reuse them as is for testing the environment. 

What do you think about it?

**Comment by tustvold** [comment]
I'm not sure I follow what you mean, and the CI seems to currently be failing?

**Comment by amrltqt** [comment]
Yes, I understand that we need (at least) the key_id, the secret_key correctly setup for the CLI to execute `aws --endpoint-url=http://localstack:4566 s3 mb s3://test-bucket`.

But, it's seems to be not needed anymore after that. I'll try to setup environment by steps as you mention.

**Comment by amrltqt** [comment]
@tustvold it should be better now. 
Sorry for not having put a draft tag on this PR at first 😅

**Review by tustvold — APPROVED** [review]
Thank you

**Pull request merged**
