### PR TITLE
Add multiply_scalar kernel

### LINKED ISSUE #1153: support more mathematics kernels for array and scalar value
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We only have `powf_scalar`, `modulus_scalar` and `divide_scalar`. We need more mathematics kernels for array and scalar value that could be used by downstream projects e.g. datafusion.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1153 .

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
cc @alamb

**Review by liukun4515 — APPROVED** [review]
LGTM

**Review by alamb — APPROVED** [review]
Thanks @viirya !

**Comment by viirya** [comment]
Thanks @alamb !

**Pull request merged**
