### PR TITLE
Expose reqwest client for AWS, Azure, and GCP clients.

### LINKED ISSUE #3127: Object Store: Allow custom reqwest client
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I am connecting to our Ceph cluster and getting intermittent connection closed errors from the server. I have tried both multipart and non-multipart uploads and have had the same issues.

Others have run into this issue with the S3 API with reqwest/hyper and have needed to change their client configuration to resolve the issue.
See:
* https://github.com/hyperium/hyper/issues/2136
* https://github.com/hyperium/hyper/issues/2136#issuecomment-861826148

**Describe the solution you'd like**

I would like to expose the reqwest client for custom configuration.

**Describe alternatives you've considered**

An alternative would be to expose individual configuration settings in the Reqwest client and continue to shield creation of the client from the end user. This seems like unnecessary complexity for the object store to expose.

Another alternative would be to make the reqwest client public so that it can be modified after the S3Client has been created. Exposing the client in this way is bad API design. Keeping the client private while allowing initial configuration seems to me to be the best route.

**Additional context**

### PR DESCRIPTION
**Pull request by freeformstu**
# Which issue does this PR close?

Closes #3127.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

There are three new public methods. One on each of the Object Store clients.

### CODE REVIEW

**Comment by tustvold** [comment]
I would prefer we expose the desired options on the builders, theoretically we could create a HttpClientOptions struct to reduce duplication. The motivation is to allow us to change the underlying HTTP client without this being a breaking change. What do you think?

**Comment by alamb** [comment]
I recommend we allow direct access to the clients as an "escape hatch" for any options that are not natively available in the object_store crate -- with suitable warnings that the interface may change in future versions. While it is a less strict abstraction, it would allow ways to set more options without waiting for a new version of object_store being released

**Comment by tustvold** [comment]
I've created https://github.com/apache/arrow-rs/pull/3252 to help with this. In particular this avoids issues that arise from the fact there may be two different clients, one used to make requests and one used to get authentication information.

**Comment by tustvold** [comment]
I'm closing this as I believe #3252 covers this use-case, please feel free to reopen if I am mistaken

**Pull request closed without merging**
