### PR TITLE
Cleanup MetadataLoader tests

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Follow on to https://github.com/apache/arrow-rs/pull/6474

# Rationale for this change
 
There were some test changes in https://github.com/apache/arrow-rs/pull/6474 that made them more complicated and were no longer necessary

# What changes are included in this PR?

Revert the changes to tests from https://github.com/apache/arrow-rs/pull/6474

# Are there any user-facing changes?

This is all internal

### CODE REVIEW

**Comment by etseidl** [comment]
take

**Comment by etseidl** [comment]
Oops, though this was an issue 😅. Thanks @alamb, that was fast. 🚀

**Comment by alamb** [comment]
> Oops, though this was an issue 😅. Thanks @alamb, that was fast. 🚀

LOL -- I had made the change locally and figured there was no reason to push to your PR or hold the PR anymore so I just merged it in

**Review by etseidl — APPROVED** [review]
Looks good and reverted. Thanks!

**Pull request merged**
