### PR TITLE
Prepare for 53.1.0 release (CHANGELOG and version)

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Part of https://github.com/apache/arrow-rs/issues/6340

# Rationale for this change
 
We are preparing for a release. 

# What changes are included in this PR?

1. Update version
2. Update CHANGELOG (see rendered version here https://github.com/alamb/arrow-rs/blob/alamb/prepare_53.1.0/CHANGELOG.md)

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
I am hoping to update the CHANGELOG one more time (to get https://github.com/apache/arrow-rs/pull/6303 and to update some tags)

**Review by mbrobbel — COMMENTED** [review]
Just noticed that the PR title has `52.1.0`, it should be `53.1.0`.

**Comment by alamb** [comment]
> Just noticed that the PR title has `52.1.0`, it should be `53.1.0`.

🤦  -- you are right. Fixed

**Comment by alamb** [comment]
https://github.com/alamb/arrow-rs/blob/alamb/prepare_53.1.0/CHANGELOG.md -- quite a nice looking release :bowtie:

**Pull request merged**
