### PR TITLE
Change `UnionArray` constructors

### LINKED ISSUE #5613: Cleanup UnionArray Constructors
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The UnionArray constructors are somewhat at odds with the pattern followed for other array types.

**Describe the solution you'd like**

I would like the signature to be updated to be

```
fn try_new(fields: UnionFields, type_ids: ScalarBuffer<i8>, offsets: Option<ScalarBuffer<i32>>, children: Vec<ArrayRef>) 
    -> Result<Self, ArrowError>
```

`into_parts` should then be updated to match

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by mbrobbel**
# Which issue does this PR close?

Closes #5613.

# Rationale for this change
 
It came up in #5585 that the `UnionArray` constructors are a bit odd when compared to the other array constructors.

# What changes are included in this PR?

## `UnionArray::try_new` and `UnionArray::new_unchecked`

Changed arguments:
From: `field_type_ids: &[i8], type_ids: Buffer, value_offsets: Option<Buffer>, child_arrays: Vec<(Field, ArrayRef)>`
To: `fields: UnionFields, type_ids: ScalarBuffer<i8>, offsets: Option<ScalarBuffer<i32>>, children: Vec<ArrayRef>`.

The order of `children` arrays must match the order of fields in the `UnionFields`.

The validation in `try_new` is a bit more strict.

## `UnionBuilder`

It now uses a `BTreeMap` instead of a `HashMap` internally to get sorted iteration.

# Are there any user-facing changes?

This is a breaking change that changes the `UnionArray` constructors.

### CODE REVIEW

**Comment by tustvold** [comment]
In light of https://github.com/apache/arrow-rs/issues/5368 I think I would like to sit on this for a bit, and we can look to get this bundled in when we next make a breaking release

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
I took the liberty of merging up main, making some minor tweaks to avoid hashmaps, and adding some additional tests. I think if you're happy this is then ready to go in (the next release is going to be breaking)

**Comment by mbrobbel** [comment]
> I took the liberty of merging up main, making some minor tweaks to avoid hashmaps, and adding some additional tests. I think if you're happy this is then ready to go in (the next release is going to be breaking)

Why would we want to avoid hashmaps/sets here?

It seems the negative `type_id` check was dropped.

**Comment by tustvold** [comment]
> Why would we want to avoid hashmaps/sets here?

They're slower, given there are only 128 possibilities and they'll almost always be clustered towards the lower end, it is faster just to use a vec

> It seems the negative type_id check was dropped.

Would you care to expand on this?

**Comment by mbrobbel** [comment]
> > Why would we want to avoid hashmaps/sets here?
> 
> They're slower, given there are only 128 possibilities and they'll almost always be clustered towards the lower end, it is faster just to use a vec
> 

Is there a benchmark? I'm wondering how much slower.

> > It seems the negative type_id check was dropped.
> 
> Would you care to expand on this?

https://github.com/apache/arrow-rs/pull/5623/commits/7cd47ded5ebe01b8086ff68bcb442166a9f6f100#diff-7e118aa8aabb6fbbb2b5dcd508dd5b3219300bcb829c6cbef6cf35146320806aR191-R199

**Comment by tustvold** [comment]
The check got moved to here - https://github.com/apache/arrow-rs/pull/5623/commits/a69cbac4466eb2967ff20d6b117d30e891596f6f#diff-7e118aa8aabb6fbbb2b5dcd508dd5b3219300bcb829c6cbef6cf35146320806aR209

> Is there a benchmark? I'm wondering how much slower.

No, but I would expect it to be quite significant. You are comparing the performance of a pointer indirection to a hashmap lookup. Given this check is done for every type in the array, I would expect it to be quite significant

**Pull request merged**
