### PR TITLE
Print the 'FixedSizeBinaryArray' like a normal 'BinaryArray'

### LINKED ISSUE #1096: Pretty printing `FixedSizeBinaryArray`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
For the moment, one cannot pretty print a `FixedSizedBinaryArray`.

**Describe the solution you'd like**
Adding a match arm to the `array_value_to_string` function to support `FixedSizedBinaryArray`. 

**Describe alternatives you've considered**
Adding a top-level function in my code that would pretty print the `FixedSizeBinaryArray` has it is not supported by this crate yet.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by GrandChaman**
# Which issue does this PR close?

Closes #1096.

# Rationale for this change
 
 
See #1096.

# What changes are included in this PR?

A new match arm has been added to the `array_value_to_string` function to allow pretty printing `FixedSizeBinaryArray`.

# Are there any user-facing changes?

Not directly.

### CODE REVIEW

**Review by liukun4515 — APPROVED** [review]
LGTM

**Review by alamb — APPROVED** [review]
Thank you @GrandChaman -- also for the test ❤️

**Comment by alamb** [comment]
The tests are failing due to an unrelated reason -- see https://github.com/apache/arrow-rs/pull/1102 -- will resolve them and get back to this

**Comment by alamb** [comment]
FYI @GrandChaman  I have merged `master` to this branch, and hopefully we'll get a clean CI run now

**Comment by alamb** [comment]
I also pushed a fix for rust fmt: https://github.com/apache/arrow-rs/pull/1097/commits/39e8326a986f93bb0fbc11bbcfb1b9c767be44d7

**Comment by alamb** [comment]
Thanks again @GrandChaman

**Pull request merged**
