### PR TITLE
Exclude some long-running tests when running under miri

### LINKED ISSUE #1862: Exclude some long-running tests from miri
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Related to #1833. Some tests take excessively long to run under miri and also consume a large amount of memory. To make the CI finish in a reasonable time we should exclude them

**Describe the solution you'd like**

The tests I noticed are
 
 - `test_dense_i32_large`
 - `fuzz_test_slices_iterator`
 - `fuzz_filter`

**Describe alternatives you've considered**

Bigger instances for CI would solve the memory usage, but the runtime would still be quite long.

### PR DESCRIPTION
**Pull request by jhorstmann**
# Which issue does this PR close?

Closes #1862.

# Rationale for this change

Stacked borrow checking uses a lot of cpu and memory resources. Disabling it should make CI much more reliable.
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — APPROVED** [review]

**Comment by jhorstmann** [comment]
This did not seem to fix CI. Test tests still seem to get killed and then retried by `miri.sh`:

```
test compute::kernels::cast_utils::tests::string_to_timestamp_timezone_space ... ok
error: test failed, to rerun pass '-p arrow --lib'
Caused by:
  process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri /home/runner/work/arrow-rs/arrow-rs/target/miri/x86_64-unknown-linux-gnu/debug/deps/arrow-ca24f64806e3ede9 --skip csv --skip ipc --skip json` (exit status: 255)
test compute::kernels::comparison::tests::ilike_utf8_scalar_escape_testing ... Starting Arrow MIRI run...
    Finished test [unoptimized + debuginfo] target(s) in 0.38s
     Running unittests src/lib.rs (target/miri/x86_64-unknown-linux-gnu/debug/deps/arrow-ca24f64806e3ede9)
running 1038 tests
test array::array::tests::test_array_ref_as_array ... ok
```

**Comment by jhorstmann** [comment]
```
error: test failed, to rerun pass '-p arrow --lib'
Caused by:
  process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri /home/runner/work/arrow-rs/arrow-rs/target/miri/x86_64-unknown-linux-gnu/debug/deps/arrow-ca24f64806e3ede9 --skip csv --skip ipc --skip json` (exit status: 255)
test compute::kernels::comparison::tests::ilike_utf8_scalar_escape_testing ... Miri finished with exit code 255
```
That's actually not the error code I expected if it is an out of memory issue

**Comment by jhorstmann** [comment]
Disabling stacked-borrow checking is not perfect, but probably better to run miri with one less check than not running it at all. The check using a lot of cpu and memory is a known problem: https://github.com/rust-lang/miri/issues/1367

**Review by tustvold — COMMENTED** [review]
This seems sensible 👍. We could conceivably run the full MIRI suite as part of release validation, or something, but I also don't feel particularly strongly about this

**Review by tustvold — APPROVED** [review]
Looks good to me

**Pull request merged**
