### PR TITLE
WIP: Fix FFI UB with arrays with child data

### PR DESCRIPTION
**Pull request by ritchie46**
# Which issue does this PR close?

See description in #20. I put this PR in a WIP state and need some help with this one.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
I am investigating this one.

**Comment by ritchie46** [comment]
> I am investigating this one.

Great! I got stuck on this, so hopefully I can learn something from it.

**Comment by nevi-me** [comment]
I don't know if I'd be useful here, but I'll also have a look at this.

**Comment by ritchie46** [comment]
Close, fixed in #287

**Pull request closed without merging**
