### PR TITLE
Implement skip_rep_levels

### LINKED ISSUE #2108: Support skip_rep_levels in ColumnLevelDecoder
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
https://github.com/apache/arrow-rs/blob/c58554453bec8f4a78d503e79576b85108b210b5/parquet/src/column/reader/decoder.rs#L84-L90
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by thinkharderdev**
# Which issue does this PR close?

Closes #2108

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by thinkharderdev** [comment]
@tustvold @Ted-Jiang Leaving this as a draft rn as I'm not sure I understand how all the pieces fit together here and what an appropriate unit test would be.

**Comment by Ted-Jiang** [comment]
@thinkharderdev Thanks for pin me, But i am not familiar with this?
I think we only need `skip_rep_levels` when need support `Complex type` 🤔
Just curious , is there a situation you need this?

**Comment by thinkharderdev** [comment]
> @thinkharderdev Thanks for pin me, But i am not familiar with this? I think we only need `skip_rep_levels` when need support `Complex type` 🤔 Just curious , is there a situation you need this?

Not anything in particular, was just trying to knock out todo items for skipping :)

**Comment by tustvold** [comment]
Would you be happy for me to pick this one up?

**Comment by thinkharderdev** [comment]
> Would you be happy for me to pick this one up?

Yes please :)

**Comment by tustvold** [comment]
Closing as #2999 has been merged

**Pull request closed without merging**
