### PR TITLE
Add _dyn kernels of like, ilike, nlike, nilike kernels for dictionary support

### LINKED ISSUE #1975: Support DictionaryArray in Like Kernels
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Noticed whilst implementing https://github.com/apache/arrow-datafusion/pull/2808, we currently lack support for dictionary arrays in the like comparison kernels

**Describe the solution you'd like**

We should support dictionary arrays in these kernels

**Describe alternatives you've considered**

We could not support them

**Additional context**
None

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1975.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — COMMENTED** [review]
We don't seem to provide `eq_dict` or `gt_dict` instead this is hidden within `eq_dyn`, perhaps we should do the same here?

**Comment by psvri** [comment]
Thanks @viirya for implementing the rest.

**Comment by viirya** [comment]
> We don't seem to provide `eq_dict` or `gt_dict` instead this is hidden within `eq_dyn`, perhaps we should do the same here?

I think it is because there are `like_dict_scalar`, `nlike_dict_scalar` etc for dictionary arrays. I agree that for other comparison kernels, only primitive and _dyn kernels are available. Maybe we should remove these `_dict_scalar` and only keep `_dyn` for dictionary support?

**Comment by tustvold** [comment]
That sounds good to me

**Review by tustvold — APPROVED** [review]
I wonder if the dictionary support should be gated behind dyn_cmp_dict?

**Pull request merged**
