### PR TITLE
Add option to `FlightDataEncoder` to always resend batch dictionaries

### LINKED ISSUE #4895: Add option to FlightDataEncoder to always send dictionaries
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Per #3389 dictionaries are not supported over flight and right now they are cast into their underlying value type array.

**Describe the solution you'd like**
In lieu of the solution described on #3389 to provide initial support for dictionary arrays we can have opt in behavior to always send dictionaries with each record batch, replacing the previous

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by alexwilcoxson-rel**
# Which issue does this PR close?

Closes #4895

# Rationale for this change
 
see #4895

# What changes are included in this PR?

Adds `with_send_dictionaries` to `FlightDataEncoderBuilder` to opt in to always sending dictionary messages with each record batch encoded.

# Are there any user-facing changes?

`with_send_dictionaries` added to `FlightDataEncoderBuilder` and `FlightDataEncoder`. Doc strings updated.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you for this PR @alexwilcoxson-rel  -- I hope to find time to review it properly in the next few days

**Review by alamb — APPROVED** [review]
Thank you @alexwilcoxson-rel -- I think this is a really nice improvement and it could be merged as is.

I was thinking to a future when we might have proper support for resending dictionaries and trying to minimize the API impact as well as adding a nice place for more documentation. What do you think about using an `enum` instead of a `bool` like this:

So instead of 
```rust
pub struct FlightDataEncoder {
...
    send_dictionaries: bool,
...
}
```

Something like 
```rust
pub struct FlightDataEncoder {
...
    dictionary_handling: DictionaryHandling,
...
}

/// Defines how a [`FlightDataEncoder`] encodes [`DictionaryArray`]s
pub enum DictionaryHandling {
  /// Expands to the underlying type (default). This likely sends more data over the network
  /// but requires less memory (dictionaries are not tracked) and is  more compatible
  /// with other arrow flight client implementations that may not support `DictionaryEncoding`
  /// see [`hydrate_dictionary`] for more details.
  Hydrate,
  /// Send dictionary FlightData with every RecordBatch that contains a [`DictionaryArray`].
  /// See [`Self::Hydrate`] for more tradeoffs
  None, 
}
```

**Comment by alamb** [comment]
BTW it looks like some documentation also needs to be updated, like https://github.com/apache/arrow-rs/blob/23db567d05bc21df56f5f7d08288f209de9fd785/arrow-flight/src/encode.rs#L33

I can handle doing so, but wanted to mention it in case @alexwilcoxson-rel was going to change this one more

**Comment by alexwilcoxson-rel** [comment]
> BTW it looks like some documentation also needs to be updated, like
> 
> https://github.com/apache/arrow-rs/blob/23db567d05bc21df56f5f7d08288f209de9fd785/arrow-flight/src/encode.rs#L33
> 
> I can handle doing so, but wanted to mention it in case @alexwilcoxson-rel was going to change this one more

Updated these docs

**Comment by alexwilcoxson-rel** [comment]
Updated to use Enum per @alamb feedback

**Review by alamb — APPROVED** [review]
Thanks @alexwilcoxson-rel  -- this looks great

**Comment by alamb** [comment]
The CI seems to be failing the doc checks. I'll try and fix that

**Comment by alamb** [comment]
Here is a proposed PR to your branch for improved documentation https://github.com/relativityone/arrow-rs/pull/1 🙏

**Comment by alexwilcoxson-rel** [comment]
> Here is a proposed PR to your branch for improved documentation [relativityone#1](https://github.com/relativityone/arrow-rs/pull/1) 🙏

LGTM, merged! please rerun CI when you can.

**Comment by alamb** [comment]
Thanks again @alexwilcoxson-rel

**Pull request merged**
