### PR TITLE
MINOR: fix indent in asf yaml

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by wesm** [comment]
Do you want to turn off merge commits + require squash merging for this repo? It's a shame to see merge commits introduced into a pristine commit history =)

**Comment by jorgecarleitao** [comment]
I agree, I love our commit history. I though that that was the first thing we did: only accept squashing.

**Comment by wesm** [comment]
It's not too late to fix, you might consider fixing this merge commit before more stuff piles up

**Comment by jorgecarleitao** [comment]
@alamb @andygrove , can I force push with this merge commit changed into a normal commit?

**Comment by alamb** [comment]
@jorgecarleitao  I am sorry I am not quite sure what you are asking

**Comment by andygrove** [comment]
@jorgecarleitao I didn't understand either but I have no objections

**Comment by jorgecarleitao** [comment]
Arrow has been using linear history, and we have not discussed changing this in the proposal. We have a merge commit in master (two parents).

The proposal is to re-write history on master to remove the offending commit, replacing it by a commit with a single parent, to keep the same linear history that we have been having so far.

**Comment by alamb** [comment]
> The proposal is to re-write history on master to remove the offending commit, replacing it by a commit with a single parent, to keep the same linear history that we have been having so far.

@jorgecarleitao  that is fine with me -- note we should do it asap to minimize the impact to outstanding PRs (they will need to be rebased probably).

**Comment by jorgecarleitao** [comment]
Done.

**Comment by andygrove** [comment]
Apologies for causing this with the indent issue. I had fixed this already
in arrow-datafusion and I assume we don't have the issue over there?

**Comment by wesm** [comment]
It was 3 days ago so probably before merge commits were disallowed in the UI.

**Pull request merged**
