### PR TITLE
feat: support reading and writing`StringView` and `BinaryView` in parquet (part 1)

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

First part of https://github.com/apache/arrow-rs/issues/5530

# Rationale for this change
 
This is the first 3 commits from  https://github.com/apache/arrow-rs/pull/5557 by @ariesdevil  for initial support of reading `StringViewArray` and `BinaryViewArray` from parquet

The performance is non ideal (it copies string data several times) but it does include benchmarks and tests. 

Thus I would like to merge this in and then continue iterating on the design in https://github.com/apache/arrow-rs/pull/5557 to keep the PRs smaller and more manageable

# What changes are included in this PR?
1. Basic support for reading/writing`StringViewArray` and `BinaryViewArray` from parquet
2. Tests for same
3. Benchmarks

# Are there any user-facing changes?
The arrow reader/writer can now read /write `StringViewArray` and `BinaryViewArray`s

### CODE REVIEW

**Comment by mapleFU** [comment]
Just a minor question: during writing parquet, arrow will serialize self-schema. Would BinaryView/StringView keep it's schema, or using Binary/String here?

**Comment by ariesdevil** [comment]
> Just a minor question: during writing parquet, arrow will serialize self-schema. Would BinaryView/StringView keep it's schema, or using Binary/String here?

View type will keep its schema

**Comment by alamb** [comment]
Merging this one in as it doesn't expose any public PRs and has been reviewed as a prior PR https://github.com/apache/arrow-rs/pull/5557#pullrequestreview-1974957324

Let's continue the conversation on https://github.com/apache/arrow-rs/pull/5557

**Comment by alamb** [comment]
Thanks again @ariesdevil and @mapleFU

**Pull request merged**
