### PR TITLE
ObjectStore: make error msg thrown from retry more detailed

### LINKED ISSUE #5013: ObjectStore: hard to determine the cause of the error thrown from retry
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I found hard to determine the cause of the error thrown from retry when using `object_store` in our project, due to not enough information in error msg.

**Describe the solution you'd like**

Add more detailed information in error msg.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Rachelint**
# Which issue does this PR close?

Closes #5013 

# Rationale for this change
I found it is difficult to locate the cause of the thrown error when using `object_store` crate in our project, due to information in error msg is not enough. So I hope such error msg can be more detailed and make it in this pr.

# What changes are included in this PR?
Add more info to the error in `object_store/src/client/retry.rs` for better debugging.

# Are there any user-facing changes?
None.

### CODE REVIEW

**Comment by Rachelint** [comment]
PTAL @tustvold @alamb

**Comment by tustvold** [comment]
I think some of the tests need updating

**Comment by Rachelint** [comment]
> I think some of the tests need updating

Ok, I will fix it soon.

**Review by alamb — COMMENTED** [review]
Thank you @Rachelint 🙏

**Comment by Rachelint** [comment]
@tustvold @alamb thanks for review :blush:
I have fixed the failed test.

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
Thank you for sticking with this :+1:

**Pull request merged**
