### PR TITLE
Reduce integration test matrix

### LINKED ISSUE #6406: Reduce integration test matrix
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

A challenge.

The current integration test uses the following test matrix:

https://github.com/apache/arrow-rs/actions/runs/10886360255/job/30206176246#step:12:62

```text
Integration: Test: IPC: C++ -> C++
Integration: Test: IPC: C++ -> Java
Integration: Test: IPC: C++ -> JS
Integration: Test: IPC: C++ -> C#
Integration: Test: IPC: C++ -> Go
Integration: Test: IPC: C++ -> Rust
Integration: Test: IPC: Java -> C++
Integration: Test: IPC: Java -> Java
Integration: Test: IPC: Java -> JS
Integration: Test: IPC: Java -> C#
Integration: Test: IPC: Java -> Go
Integration: Test: IPC: Java -> Rust
Integration: Test: IPC: JS -> C++
Integration: Test: IPC: JS -> Java
Integration: Test: IPC: JS -> JS
Integration: Test: IPC: JS -> C#
Integration: Test: IPC: JS -> Go
Integration: Test: IPC: JS -> Rust
Integration: Test: IPC: C# -> C++
Integration: Test: IPC: C# -> Java
Integration: Test: IPC: C# -> JS
Integration: Test: IPC: C# -> C#
Integration: Test: IPC: C# -> Go
Integration: Test: IPC: C# -> Rust
Integration: Test: IPC: Go -> C++
Integration: Test: IPC: Go -> Java
Integration: Test: IPC: Go -> JS
Integration: Test: IPC: Go -> C#
Integration: Test: IPC: Go -> Go
Integration: Test: IPC: Go -> Rust
Integration: Test: IPC: Rust -> C++
Integration: Test: IPC: Rust -> Java
Integration: Test: IPC: Rust -> JS
Integration: Test: IPC: Rust -> C#
Integration: Test: IPC: Rust -> Go
Integration: Test: IPC: Rust -> Rust
```

But `${lang1 in apache/arrow} -> ${lang2 in apache/arrow}` such as `C++ -> Java` are needless in apache/arrow-rs. Because they should be tested in apache/arrow's integration test.

We need only the following patterns:

```text
Integration: Test: IPC: C++ -> Rust
Integration: Test: IPC: Java -> Rust
Integration: Test: IPC: JS -> Rust
Integration: Test: IPC: C# -> Rust
Integration: Test: IPC: Go -> Rust
Integration: Test: IPC: Rust -> C++
Integration: Test: IPC: Rust -> Java
Integration: Test: IPC: Rust -> JS
Integration: Test: IPC: Rust -> C#
Integration: Test: IPC: Rust -> Go
Integration: Test: IPC: Rust -> Rust
```

This will reduce test time. (The current test time: 10m 50s)

See also: apache/arrow#44062

**Describe the solution you'd like**

Use apache/arrow#44099 change something like https://github.com/apache/arrow/issues/44062#issuecomment-2350266865 .

**Describe alternatives you've considered**

None.

**Additional context**

None.

### PR DESCRIPTION
**Pull request by kou**
# Which issue does this PR close?

Closes #6406.

# Rationale for this change
 
This is for reducing test time.

# What changes are included in this PR?

Use new `ARCHERY_INTEGRATION_TARGET_IMPLEMENTATIONS` option introduced in apache/arrow#44099 and apache/arrow#44156.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by kou** [comment]
Reduced:

https://github.com/apache/arrow-rs/actions/runs/10894287556/job/30230774799?pr=6407#step:12:65

```text
Integration: Test: IPC: Rust -> Rust
Integration: Test: IPC: Rust -> C++
Integration: Test: IPC: Rust -> Java
Integration: Test: IPC: Rust -> JS
Integration: Test: IPC: Rust -> C#
Integration: Test: IPC: Rust -> Go
Integration: Test: IPC: C++ -> Rust
Integration: Test: IPC: Java -> Rust
Integration: Test: IPC: JS -> Rust
Integration: Test: IPC: C# -> Rust
Integration: Test: IPC: Go -> Rust
Integration: Test: IPC: Gold: Rust
Integration: Test: IPC: Rust -> Rust
```

Test time: 10m 50s -> 1m 44s

**Review by alamb — APPROVED** [review]
Thank you @kou! A 10x performance improvement is pretty amazing. 

I double checked the CI run for this PR https://github.com/apache/arrow-rs/actions/runs/10894287556/job/30230774799?pr=6407

And it appears to be correctly running the necessary tests

Screenshot 2024-09-17 at 12 10 22 PM

❤️  thanks again

**Comment by kou** [comment]
Sorry. We may rename the environment variable to `..._IMPLEMENTATIONS` from `..._LANGUAGES`: https://github.com/apache/arrow/pull/44156

Please wait for a while...

**Comment by kou** [comment]
Updated. It still works:

https://github.com/apache/arrow-rs/actions/runs/10933530663/job/30352151242?pr=6407#step:12:66

```text
Integration: Test: IPC: Rust -> Rust
Integration: Test: IPC: Rust -> C++
Integration: Test: IPC: Rust -> Java
Integration: Test: IPC: Rust -> JS
Integration: Test: IPC: Rust -> C#
Integration: Test: IPC: C++ -> Rust
Integration: Test: IPC: Java -> Rust
Integration: Test: IPC: JS -> Rust
Integration: Test: IPC: C# -> Rust
Integration: Test: IPC: Gold: Rust
Integration: Test: IPC: Rust -> Rust
```

**Review by Dandandan — APPROVED** [review]

**Pull request merged**
