### PR TITLE
Add ArrowError::ArithmeticOverflow

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

N/A

# Rationale for this change
 

Downstream crates (such as DataFusion Comet) often need specific handling for overflow errors and we currently have no good way to detect them other than looking for specific words in error messages, which is not very robust. For example, we currently have code like this:

```rust
match self.inner_abs_func.invoke(args) {
    Err(DataFusionError::ArrowError(ArrowError::ComputeError(msg), trace)) if msg.contains("overflow") => { ... }
```

It would be better if Arrow had an `ArithmeticOverflow` variant in the `ArrowError` enum, similar to the existing `DivideByZero` variant.

# What changes are included in this PR?

Add `ArithmeticOverflow` and update existing overflow handling.

# Are there any user-facing changes?

Yes, overflows will produce a different error now.

### CODE REVIEW

**Comment by tustvold** [comment]
This makes sense to me, we should possibly make ArrowError non_exhaustive to avoid adding new variants being a breaking in future.

Unfortunately this has now missed the release and so will have to wait until the next breaking release which will be in 3 months time...

**Comment by tustvold** [comment]
> Then we can backport any fixes needed to 52.0.0_maintenance and keep development churning along on master

I think I would rather avoid reaching for git-flow style branch machinery until we have either:

* A non-trivial number of pending breaking changes
* Dependent / conflicting breaking changes that need to be applied in a particular order

Otherwise I think we're just creating work for ourselves.

I would prefer we mark this as a draft, and then look to bring it in once either the above criteria occur, or it is time for the breaking release.

**Comment by tustvold** [comment]
I had understood we were going to do monthly minor releases, i.e. not just patch releases of back-ported fixes? I presume in your proposed model these would have to come from the maintenance branch, which implies mirroring most commits across

**Comment by alamb** [comment]
> I had understood we were going to do monthly minor releases, i.e. not just patch releases of back-ported fixes? I presume in your proposed model these would have to come from the maintenance branch, which implies mirroring most commits across

I think the key question is "what do we want in the monthly releases" and thus "what is the criteria to include code there"

**Comment by tustvold** [comment]
> I would personally selfishly likely go with the latter as it would reduce overall maintainer burden

If you adopt the branching model you propose then yes, I feel fairly confident the former model is what people are more likely to expect/want. If I implement a non-breaking feature addition / performance improvement I would not expect to have to wait 3 months, or pester a maintainer for it to be usable.

A ticket is worthwhile given you appear to feel differently on this

**Comment by alamb** [comment]
> I feel fairly confident the model that doesn't require additional ceremony for non-breaking changes is what people are more likely to expect/want

I agree. That doesn't me the maintainers are going to do it for them. 

> If I implement a non-breaking feature addition / performance improvement I would not expect to have to wait 3 months, or pester a maintainer for it to be usable. 

My idea is that there is no pestering required -- the person would simply create the cherry-pick themselves. I will file a ticket tomorrow

**Comment by alamb** [comment]
I filed https://github.com/apache/arrow-rs/issues/5907 to track the question on how to do releases and what to do with PRs such as this

**Comment by alamb** [comment]
Per discussion on https://github.com/apache/arrow-rs/issues/6050 I retargeted this PR tothe `53.0.0-dev` feature branch, where we are collecting PRs with breaking changes before `master` opens

**Comment by alamb** [comment]
I rebased this branch to target the 53.0.0 dev branch but somehow messed up the commit author. @andygrove  can you double check that this PR still looks good to you (and/or fix the author?)

**Comment by alamb** [comment]
I merged the 53 dev branch and that seems to have closed this PR -- any chance you can reopen and retarget main?

**Pull request closed without merging**
