### PR TITLE
Revert "update nightly version for miri (#1189)"

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-rs/issues/1198

# Rationale for this change
 Master CI checks seem to be broken

# What changes are included in this PR?
This reverts commit 548c96101e9f9cb06099a630d7d58f6a4e70f2f9.

# Are there any user-facing changes?

No (this just controls what version of Rust is used in CI checks)

### CODE REVIEW

**Comment by alamb** [comment]
🤔  this did not seem to solve the problem either. Will have to dig deeper maybe later today if no one beats me to it

**Comment by gangliao** [comment]
It still installs the latest nightly code: https://github.com/apache/arrow-rs/runs/4853953542?check_suite_focus=true#step:6:7

**Comment by gangliao** [comment]
```bash
11s
Run rustup toolchain install nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2022-01-18, rust version 1.60.0-nightly (ee5d8d37b 2022-01-17)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'

  nightly-x86_64-unknown-linux-gnu installed - rustc 1.60.0-nightly (ee5d8d37b 2022-01-17)

info: checking for self-updates
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'

info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.60.0-nightly (ee5d8d37b 2022-01-17)

info: downloading component 'rustfmt'
info: installing component 'rustfmt'
```

**Comment by Jimexist** [comment]
thanks for the change. in my opinion it was hardly the reason. either way just bumping a nightly version in CI wouldn't be the cause of a breakage (if it were, it were merely exposing a false negative).

i remember we had a good fight with miri some months ago. at the end @alamb you had to disable miri for a while...

**Comment by alamb** [comment]
Yeah I agree that the upgrade of nightly version doesn't seem to have caused this issue; 
All the checks passed on https://github.com/apache/arrow-rs/pull/1189 -- https://github.com/apache/arrow-rs/pull/1189/checks

I suspect that this is related to some crate being released that was not actually 'semver' compatible in some way

**Pull request closed without merging**
