### PR TITLE
Sliceable BitMap

### LINKED ISSUE #1802: Sliceable BitMap
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently `BitMap` is a simple wrapper around a `Buffer`. This limits it to slicing on multiples of 8, as `Buffer` can only slice at byte boundaries.

**Describe the solution you'd like**

Add an offset and length to `BitMap`, updating the accessors to take this into account. This may require deprecating and removing `buffer_ref`, and/or making it panic if non-zero offset.

Add a slice method to `BitMap` that uses the offset and length to perform zero-copy slicing.

**Describe alternatives you've considered**

We could not do this.

**Additional context**

Feeds into https://github.com/apache/arrow-rs/issues/1799

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1802.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
I wonder if this needs to be a new type, there is a non-trivial amount of code that has an implicit assumption that Bitmap is just a wrapper around a `Buffer`

**Comment by viirya** [comment]
Yea, if you have also looked at my previous PR (closed) for this, it involved more code change. Almost everywhere we currently return null buffer/bitmap and access it needs to be changed. So opened this one to try to have less change if possible.

Seems a good idea to be a new type for it. I will try it in the weekend.

**Comment by tustvold** [comment]
I plan to add a `BooleanBuffer` type as part of #1176 which should fit this use-case

**Comment by viirya** [comment]
Close in favor of #3749

**Pull request closed without merging**
