### PR TITLE
Enable wasm32 as a target architecture for the SIMD feature 

### LINKED ISSUE #316: Add wasm32 to the list of target architectures of the simd feature
packed_simd compiles to wasm32-wasi and wasm32-unknown-unknown targets (and includes CI against it). It will only work on WASM runtimes that support the WASM SIMD proposal but that's no reason to block it from arrow-rs side.

**Describe the solution you'd like**

Add wasm32 to https://github.com/apache/arrow-rs/blob/c863a2c44bffa5c092a49e07910d5e9225483193/arrow/build.rs#L24

**Describe alternatives you've considered**

Optional features should not be limited to specific architectures in arrow-rs itself. The arrow-rs CI shouldn't run tests with combinations that are not known to work, but as a user I would expect that if I enable a feature then it's enabled (and might create a failure on its own if it doesn't work yet). It took me a while to understand why I get the error described in #232 when targeting wasm32. This would probably require changes to the CI workflows though.

### PR DESCRIPTION
**Pull request by roee88**
# Which issue does this PR close?

Closes #316

 # Rationale for this change
 
packed_simd compiles to wasm32-wasi and wasm32-unknown-unknown targets (and includes CI against it). It will only work on WASM runtimes that support the WASM SIMD proposal but that's no reason to block it from arrow-rs side.

# What changes are included in this PR?

Same as https://github.com/apache/arrow-rs/pull/303 but without limiting to specific architectures. The rationale is described in #316:

> Optional features should not be limited to specific architectures in arrow-rs itself. The arrow-rs CI shouldn't run tests with combinations that are not known to work, but as a user I would expect that if I enable a feature then it's enabled (and might create a failure on its own if it doesn't work yet).

If this turns out to be a problem with the CI then I will revert to just adding `wasm32` to build.rs. 

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
cc @houqp

**Review by alamb — APPROVED** [review]
This seems like a fine change to me. As @jorgecarleitao  probably found, this configuration was added in https://github.com/apache/arrow-rs/commit/73b7576e33058c199faec403530e7a43f7f87d1e by @houqp  so I think it would be good if he wanted to weigh in

**Comment by roee88** [comment]
Sure. Though I don't think that the link you shared actually affects it. Originally there was no feature flag for simd and it was always enabled for x86 and x86_64. Then, a feature flag was added on top to allow disabling simd, it was then and set to disable by default, then cfg_aliases  was used (no functionality change), and finally aarch64 was added to the list of architectures. 

So I might be wrong but it all seems to be for historic reasons. However, thus applies only as long as it's disabled by default. If at some point it will change to enable by default it would need to be enabled by default only for known supported architectures and disabled by default otherwise. Is that something that's possible to implement easily?

**Comment by alamb** [comment]
Yeah, this looks good to me

I tested (on a mac, with the most recently updated nightly buid)
```
cargo +nightly build  --target=wasm32-unknown-unknown  --features=simd   -p arrow
```

and it built 👍

**Comment by houqp** [comment]
Apologize for missing the ping, yes, the cfg_aliases was added with the goal to not introduce any functioning change at the time. I am all for simplifying it to use the native feature flag and let build fail for unsupported architectures :)

**Pull request merged**
