### PR TITLE
Add a cast test case for decimal negative scale

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #.

# Rationale for this change
 

Clarifying the question at https://github.com/apache/arrow-rs/pull/3139#issuecomment-1327945474.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
Although I wonder if this should be returning an error?

**Comment by viirya** [comment]
> Although I wonder if this should be returning an error?

Why? I think this is correct behavior.

**Comment by tustvold** [comment]
For other types we error on truncation, so I figured we would do the same here, if you're fine with truncation why not just use floats? I dunno, I'm not very knowledgeable about decimals, so happy to defer to you 😅

**Comment by viirya** [comment]
> For other types we error on truncation, so I figured we would do the same here, if you're fine with truncation why not just use floats? I dunno, I'm not very knowledgeable about decimals, so happy to defer to you 😅

This follows current rounding behavior when casting between decimals with different scales. It rounds to nearest neighbor and round up when both neighbors are equidistant. I added one more test to make it more clear.

**Review by tustvold — APPROVED** [review]

**Pull request merged**
