### PR TITLE
Minor: Remove cloning ArrayData in with_precision_and_scale

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #.

# Rationale for this change
 

`with_precision_and_scale` doesn't need `self` actually but only a reference.

And more, usually we get a reference of decimal array with APIs like `as_primitive_array`. Currently it makes harder to call `with_precision_and_scale` with that.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — COMMENTED** [review]
Would it need self if we changed it to not clone ArrayData?

**Comment by viirya** [comment]
The main pain point of current API is that the reference of primitive array returned from `as_primitive_array`, cannot be called with it.

**Comment by viirya** [comment]
@tustvold Do you have more thoughts on this?

**Comment by tustvold** [comment]
I think a `with_` taking by reference is somewhat at odds with the rest of the codebase. It is primarily intended for use when building new array, at which point cloning the ArrayData is just an unnecessary overhead. In the downcast case you mention currently one can do

```
DecimalArray::from(array.data().clone()).with_precision_and_scale(p, s).unwrap()
```

i.e. explicitly clone the array data, and this is actually less verbose than downcasting it. So I'm not sure about this...

**Comment by viirya** [comment]
> `DecimalArray::from(array.data().clone()).with_precision_and_scale(p, s).unwrap()`

This works, though it's not straightforward to use the API.

But as the cloning seems not able to be removed, maybe it is better to make the API more easy to use with a reference?

**Comment by tustvold** [comment]
The cloning is not necessary in the very common case of building a new array

**Comment by viirya** [comment]
Ah, you're right. Not realized that we can directly use `data` here...

**Review by tustvold — APPROVED** [review]

**Pull request merged**
