### PR TITLE
Increase output scale for decimal division

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #.

# Rationale for this change
 

https://github.com/apache/arrow-datafusion/issues/6828

# What changes are included in this PR?

# Are there any user-facing changes?

Honestly not sure, this does change the output types for some decimal arithmetic, whether that counts as a breaking change is potentially debatable given this is not something documented, and regardless is a very recent feature addition.

### CODE REVIEW

**Comment by westonpace** [comment]
This covers the first part of the rules but will quickly reach overflow if you combine operations without using the second rules to reduce scale:

```
  private static Decimal adjustScaleIfNeeded(int precision, int scale) {
    if (precision > MAX_PRECISION) {
      int minScale = Math.min(scale, MIN_ADJUSTED_SCALE);
      int delta = precision - MAX_PRECISION;
      precision = MAX_PRECISION;
      scale = Math.max(scale - delta, minScale);
    }
    return new Decimal(precision, scale, 128);
  }
```

**Comment by tustvold** [comment]
> using the second rules to reduce scale

Is this not covered by `min(T::MAX_SCALE)`?

**Comment by tustvold** [comment]
@westonpace I'm having a hard time following the logic behind adjustScaleIfNeeded. I can understand truncating the scale of the output in order to make it fit, however, the MIN_ADJUSTED_SCALE part doesn't make sense to me. It acts to clamp the scale to be <= 6, but without this having an impact on the output precision, which seems to be incorrect?

Say I the computed output had a scale of 10 and a precision of 40, adjustScaleIfNeeded would then clamp this to a scale of 6 and a precision of 38. I would have thought it would either clamp to a scale of 8 and precision of 38, or a scale of 6 and a precision of 36?

**Comment by tustvold** [comment]
I've filed https://github.com/apache/arrow-rs/issues/4664 and have a preliminary implementation of what it would take to support precision-loss decimal arithmetic. I hope to polish this up over the coming week

**Comment by tustvold** [comment]
Decided to not move forward with this, see https://github.com/apache/arrow-rs/issues/4664#issuecomment-1676091528

**Pull request closed without merging**
