### PR TITLE
CI: Only run coverage jobs on master

### PR DESCRIPTION
**Pull request by alamb**
~Draft until  https://github.com/apache/arrow-rs/pull/2212~

# Which issue does this PR close?
re https://github.com/apache/arrow-rs/issues/2149

# Rationale for this change
 
The codecov job is long ([example](https://github.com/apache/arrow-rs/runs/7564428465?check_suite_focus=true) takes 20 minutes, and I haven't seen its results referred to in PRs myself. 

It also has several unfortunate issues (like not accounting for coverage of doc tests), which we should probably file as a separate issue if anyone is looking at its results.

Thus, let's only run it on pushes to master

# What changes are included in this PR?

1. Only run coverage job on pushes to master

# Are there any user-facing changes?
no

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
Won't this mean we lose information about test coverage in PRs? I personally don't regular inspect this, but some people might?

**Comment by alamb** [comment]
> Won't this mean we lose information about test coverage in PRs?

Yes that is correct.

@nevi-me  @HaoYang670 @jhorstmann @viirya @sunchao  do you ever use the per PR code coverage report ? I am proposing to only run coverage jobs on master to improve our CI

**Comment by alamb** [comment]
> llvm-cov is generally faster than tarpaulin though, so I'll explore getting it to run without the action above

Thanks @nevi-me  !

Note there is already one simple action in the `arrow-rs` repository https://github.com/apache/arrow-rs/tree/master/.github/actions/setup-builder in case you wanted to add another for coverage

**Comment by alamb** [comment]
Marking as a draft so we don't merge this PR accidentally

**Comment by alamb** [comment]
For what it is worth I don't think this ticket is super high priority -- I was just going through all the CI checks in general (on the occasion of the `object_store` crate being merged and making the current intertwined ness just a bit too much to bear).

**Comment by viirya** [comment]
I personally don't use it too much, so the idea of running coverage jobs on master is okay for me. But @nevi-me's proposal is awesome if it works. Thanks @nevi-me for working on it.

**Review by Jimexist — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Review by sunchao — APPROVED** [review]

**Comment by tustvold** [comment]
Shall we update and get this one in, there seems to be fairly broad consensus?

**Comment by alamb** [comment]
> Shall we update and get this one in, there seems to be fairly broad consensus?

👍  I will do so. We'll save some CO2 and maybe help the other PRs to run a bit faster. We can always re-enable if someone wants to see it.

**Comment by alamb** [comment]
I don't really know how to test this other than on master, so YOLO here we go:

**Comment by alamb** [comment]
Well, this is promising -- the job is queued to run on the master commit: 

https://github.com/apache/arrow-rs/commit/5166a08600fa8b356808b3fecf484f6523020f7f

https://github.com/apache/arrow-rs/runs/7679145290?check_suite_focus=true

**Pull request merged**
