### PR TITLE
Fix DoPutUpdateResult

### LINKED ISSUE #2403: Flight SQL Server sends incorrect response for `DoPutUpdateResult`
**Describe the bug**

The Flight SQL Server incorrectly does a `as_any()` and sends a protobuf enum instead of the message itself. This is incompatible with the JDBC implementation. (As usual, the spec itself is unclear). It results in the `record_count` being `0` instead of `-1` which means a proper client implementation will poll forever.

**To Reproduce**

This one is a doozy to reproduce:

1. Run [this fork](https://github.com/avantgardnerio/arrow-ballista/tree/bg_session) of ballista 
2. Build [this fork](https://github.com/avantgardnerio/arrow/tree/bg_auth2) of the JDBC driver
3. Install the fat jar driver into [your favorite](https://www.jetbrains.com/datagrip/download/#section=linux) SQL tool
4. Run an update query, observe the tool hang as it follows [the spec](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#getMoreResults(int)) attempting to wait for the condition to be met:

```
There are no more results when the following is true:

     // stmt is a Statement object
     ((stmt.getMoreResults(current) == false) && (stmt.getUpdateCount() == -1))
```

**Expected behavior**

The query succeeds.

### PR DESCRIPTION
**Pull request by avantgardnerio**
# Which issue does this PR close?

Closes #2403.

# Rationale for this change
 
My company would like to have JDBC/ODBC support work so that we can develop a market offering on top of Ballista.

# What changes are included in this PR?

Update the responses to follow the spec and be compatible with the JDBC implementation.

# Are there any user-facing changes?

Queries shouldn't hang forever.

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
I wonder if there are any other erroneous uses of as_any in this file?

**Comment by andygrove** [comment]
@wangfenjin fyi

**Comment by andygrove** [comment]
It would be nice if we could eventually add some tests for this

**Comment by tustvold** [comment]
I created a high-level ticket for some form of integration testing - https://github.com/apache/arrow-rs/issues/2409

I've left it fairly brief as I'm probably not the right person to flesh it out, as my knowledge of FlightSQL is pretty limited, but I agree it would be a good thing to have

**Comment by avantgardnerio** [comment]
> some form of integration testing

100%. I think this is the right way to go. I can probably take that one on. I'm experienced with it, and I think it's the type of testing that will catch problems like this.

**Pull request merged**
