### PR TITLE
Update twox-hash requirement from 1.6 to 2.0

### PR DESCRIPTION
**Pull request by crepererum**
Replaces #6677.

### CODE REVIEW

**Review by tustvold — APPROVED** [review]

**Comment by crepererum** [comment]
Ahh, MSRV for that crate is now Rust 1.81. I guess that's too new?

**Comment by tustvold** [comment]
> MSRV for that crate is now Rust 1.81

That is quite aggressively recent, having only been released in September. Perhaps we should sit on this for a bit?

**Comment by alamb** [comment]
See also https://github.com/apache/arrow-rs/pull/6583 from @shepmaster

**Comment by crepererum** [comment]
Closing in favor of #6583.

**Pull request closed without merging**
