### PR TITLE
Modify decimal regex to accept positive exponent specifier

### PR DESCRIPTION
**Pull request by jdcasale**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-rs/issues/5648

# Rationale for this change
If users have float data in scientific format with a positive exponent specifier (e.g "3.106e+04"), the current csv inference mechanism does not work correctly. This change fixes that. 

# What changes are included in this PR?

# Are there any user-facing changes?

This causes a change in schema inference behavior -- it's possible that some user relies on the fact that the current behavior is incorrect. I'm not sure what arrow's policy is around visible changes like this, so if this is change is not allowable I understand.

### CODE REVIEW

**Comment by tustvold** [comment]
Could we get a test or two for this please

**Comment by jdcasale** [comment]
Sure -- will add a couple of tests

**Comment by jdcasale** [comment]
@tustvold I've added a test asserting correctness of the result of inferring a schema on float data that includes scientific notation data. (with both positive and negative exponents) 

I modeled it on adjacent tests so I don't think the test itself is likely to be controversial, but this is my first-time committing to this repository so please do let me know if there's anything else you'd like to see on this.

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
Thank you, looks good to me

**Pull request merged**
