### PR TITLE
replace #[cfg(simd)] with #[cfg(feature = "simd")]

### LINKED ISSUE #232: cargo doc fails with  cannot find function `bitwise_bin_op_simd_helper` when using features=["simd"]
This was noticed by @ritchie46 

cargo doc fails with `cannot find function bitwise_bin_op_simd_helper` when using features=["simd"]

**To Reproduce**
Create a new empty repo

```terminal
$ cargo new --bin repro
```

Add
```toml
arrow = {version="4.0.0", default-features = false, features=["simd"]}
```
to Cargo.toml

Then try to build docs:
```
cd repro
cargo +nightly doc --all-features
```

The build fails:

```
    Checking arrow v4.0.0
error[E0425]: cannot find function `bitwise_bin_op_simd_helper` in this scope
   --> /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.0.0/src/buffer/ops.rs:258:9
    |
125 | / pub fn bitwise_bin_op_helper<F>(
126 | |     left: &Buffer,
127 | |     left_offset_in_bits: usize,
128 | |     right: &Buffer,
...   |
152 | |     buffer.into()
153 | | }
    | |_- similarly named function `bitwise_bin_op_helper` defined here
...
258 |           bitwise_bin_op_simd_helper(
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `bitwise_bin_op_helper`

error[E0425]: cannot find function `bitwise_bin_op_simd_helper` in this scope
   --> /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.0.0/src/buffer/ops.rs:369:9
    |
125 | / pub fn bitwise_bin_op_helper<F>(
126 | |     left: &Buffer,
127 | |     left_offset_in_bits: usize,
128 | |     right: &Buffer,
...   |
152 | |     buffer.into()
153 | | }
    | |_- similarly named function `bitwise_bin_op_helper` defined here
...
369 |           bitwise_bin_op_simd_helper(
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `bitwise_bin_op_helper`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `arrow`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Expected behavior**
Documentation builds successfully, without error

### PR DESCRIPTION
**Pull request by ritchie46**
This fixes #232. 

I really wonder if `#[cfg(simd)]` was correct at all? I couldn't find any documentation backing it, and my IDE showed the code as deactivated no matter what I did (not a really convincing reason, I know :stuck_out_tongue_winking_eye: )

Anyhow, I was able to activate "simd" as a single feature gate:

```toml
arrow = {version="5.0.0-SNAPSHOT", git = "https://github.com/ritchie46/arrow-rs", branch = "feat_simd", default-features=false, features = ["simd"]}
```

And could also compile the docs with: 

`$ cargo +nightly doc --all-features`

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
🤯

**Comment by jhorstmann** [comment]
I remember the PR that introduced that added some [build.rs magic][1] using the [cfg_alias crate][2], but I never verified that actually worked.

 [1]: https://github.com/apache/arrow-rs/blob/master/arrow/build.rs#L24
 [2]: https://docs.rs/cfg_aliases/0.1.1/cfg_aliases/

**Comment by jorgecarleitao** [comment]
I did confirm that there was a performance change back then; I also saw the performance difference when compiled with `simd` about a month ago, although I was only using it on the benches; e.g. `cargo bench --bench X --feature simd`.

Could it be that this does not work when the crate is used as a dependency?

**Comment by ritchie46** [comment]
> Could it be that this does not work when the crate is used as a dependency?

Maybe the mentioned build.rs does not run in such a case? As a dependency, you can also not compile arrow with the `"simd"` feature, so there must be something different.

**Comment by roee88** [comment]
> I remember the PR that introduced that added some [build.rs magic](https://github.com/apache/arrow-rs/blob/master/arrow/build.rs#L24) using the [cfg_alias crate](https://docs.rs/cfg_aliases/0.1.1/cfg_aliases/), but I never verified that actually worked.

Is it intentional that simd can't be enabled for wasm32 targets?

**Comment by ritchie46** [comment]
I understand that the CI fails because we don't check architectures. Does the `build.rs` file not run, when used as a crate dependency? 

Shall I go for the verbose option?:

```
#[cfg(all(any(target_arch = "x86", target_arch = "x86_64", target_arch = "aarch64"), feature = "simd")]
```

**Comment by jhorstmann** [comment]
> Is it intentional that simd can't be enabled for wasm32 targets?

Wasm does not seem to be listed as a [supported platform by packed_simd][1]. I don't have any experience with wasm, but I see no real reason why it should not work if llvm has support for it.

 [1]: https://crates.io/crates/packed_simd_2#user-content-platform-support

**Comment by ritchie46** [comment]
I am closing this, as it seems already fixed. See #232

**Pull request closed without merging**
