### PR TITLE
Improve `LIKE` performance for "contains" style queries

### PR DESCRIPTION
**Pull request by samuelcolvin**
# Which issue does this PR close?

This is will have some trivial conflicts after #6118, it's part of #6107

# Rationale for this change
 
Lots of context in #6107, this makes `LIKE` queries which are simply "conatins" significantly faster.

Running

```bash
 cargo bench -p arrow --bench comparison_kernels -F test_utils -- 'like.*contains'
```

Gives a max of ~50% speedup, but the default haystack size is 4 characters, if you increase that to 400, the performance improvement is quite marked!

```
➤ cargo bench -p arrow --bench comparison_kernels -F test_utils -- 'like.*contains'
   Compiling arrow-string v52.2.0 (/Users/samuel/code/arrow-rs/arrow-string)
   Compiling arrow v52.2.0 (/Users/samuel/code/arrow-rs/arrow)
    Finished `bench` profile [optimized] target(s) in 4.09s
     Running benches/comparison_kernels.rs (target/release/deps/comparison_kernels-95ab196215ed59e6)
like_utf8 scalar contains
                        time:   [888.14 µs 889.44 µs 891.07 µs]
                        change: [-80.213% -80.152% -80.091%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 14 outliers among 100 measurements (14.00%)
  5 (5.00%) high mild
  9 (9.00%) high severe

Benchmarking like_utf8view scalar contains: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 8.9s, or reduce sample count to 50.
like_utf8view scalar contains
                        time:   [89.263 ms 89.328 ms 89.402 ms]
                        change: [-50.303% -50.217% -50.124%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe

nlike_utf8 scalar contains
                        time:   [890.63 µs 895.93 µs 902.48 µs]
                        change: [-80.369% -80.298% -80.223%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) high mild
  6 (6.00%) high severe

ilike_utf8 scalar contains
                        time:   [31.714 ms 31.793 ms 31.876 ms]
                        change: [+1.9043% +2.1414% +2.4089%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

nilike_utf8 scalar contains
                        time:   [31.459 ms 31.508 ms 31.560 ms]
                        change: [+0.8653% +1.0474% +1.2321%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```

# What changes are included in this PR?

Use [`memchr`](https://docs.rs/memchr/latest/memchr/index.html) (which was already a dependency) instead of `str.contains`.

# Are there any user-facing changes?

AFAIK, no.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thanks again for this @samuelcolvin 

I ran the benchmarks and it looks like most of them are significantly faster but there are a few that are slower

```
group                                              contains-performance                   master
-----                                              --------------------                   ------
ilike_utf8 scalar complex                          1.00    301.9±1.12µs        ? ?/sec    1.09    329.2±1.19µs        ? ?/sec
ilike_utf8 scalar contains                         1.01   1528.2±7.46µs        ? ?/sec    1.00   1513.1±5.44µs        ? ?/sec
ilike_utf8 scalar ends with                        1.00    234.0±0.46µs        ? ?/sec    1.05    246.7±0.47µs        ? ?/sec
ilike_utf8 scalar equals                           1.00    214.5±0.46µs        ? ?/sec    1.16    248.7±0.60µs        ? ?/sec
ilike_utf8 scalar starts with                      1.00    279.5±0.35µs        ? ?/sec    1.03    286.5±0.60µs        ? ?/sec
ilike_utf8_scalar_dyn dictionary[10] string[4])    1.79     88.1±0.11µs        ? ?/sec    1.00     49.1±0.08µs        ? ?/sec
like_utf8 scalar complex                           1.00    282.6±0.67µs        ? ?/sec    1.10    310.3±1.12µs        ? ?/sec
like_utf8 scalar contains                          1.18    411.2±2.47µs        ? ?/sec    1.00    349.2±1.11µs        ? ?/sec
like_utf8 scalar ends with                         1.04    218.3±0.36µs        ? ?/sec    1.00    209.0±0.34µs        ? ?/sec
like_utf8 scalar equals                            1.00    194.6±0.29µs        ? ?/sec    1.00    195.3±0.56µs        ? ?/sec
like_utf8 scalar starts with                       1.00    230.9±0.51µs        ? ?/sec    1.00    231.3±2.18µs        ? ?/sec
like_utf8_scalar_dyn dictionary[10] string[4])     1.80     88.1±0.16µs        ? ?/sec    1.00     49.1±0.11µs        ? ?/sec
like_utf8view scalar complex                       1.01    535.4±3.00ms        ? ?/sec    1.00    532.5±1.14ms        ? ?/sec
like_utf8view scalar contains                      1.00    137.5±1.02ms        ? ?/sec    2.81    386.0±0.70ms        ? ?/sec
like_utf8view scalar ends with                     1.00     59.9±0.21ms        ? ?/sec    1.02     61.2±0.31ms        ? ?/sec
like_utf8view scalar equals                        1.08     36.7±0.11ms        ? ?/sec    1.00     34.1±0.11ms        ? ?/sec
like_utf8view scalar starts with                   1.00     60.3±0.21ms        ? ?/sec    1.01     60.8±0.18ms        ? ?/sec
nilike_utf8 scalar complex                         1.00    300.3±1.17µs        ? ?/sec    1.10    329.5±1.42µs        ? ?/sec
nilike_utf8 scalar contains                        1.01   1526.2±3.46µs        ? ?/sec    1.00   1511.7±6.28µs        ? ?/sec
nilike_utf8 scalar ends with                       1.00    234.0±0.43µs        ? ?/sec    1.06    246.9±0.43µs        ? ?/sec
nilike_utf8 scalar equals                          1.00    214.2±0.25µs        ? ?/sec    1.16    248.8±1.36µs        ? ?/sec
nilike_utf8 scalar starts with                     1.00    279.6±0.45µs        ? ?/sec    1.02    286.5±0.32µs        ? ?/sec
nlike_utf8 scalar complex                          1.00    281.3±1.06µs        ? ?/sec    1.10    310.0±1.04µs        ? ?/sec
nlike_utf8 scalar contains                         1.18    411.0±0.69µs        ? ?/sec    1.00    349.1±0.54µs        ? ?/sec
nlike_utf8 scalar ends with                        1.04    218.4±0.30µs        ? ?/sec    1.00    209.2±0.29µs        ? ?/sec
nlike_utf8 scalar equals                           1.00    194.6±0.32µs        ? ?/sec    1.00    194.8±0.27µs        ? ?/sec
nlike_utf8 scalar starts with                      1.00    230.7±0.53µs        ? ?/sec    1.00    230.6±0.24µs        ? ?/sec
```

**Comment by alamb** [comment]
What I am hoping is that we can investigate / fix the measured regressions and then merge it in 🚀

**Comment by samuelcolvin** [comment]
I can the benchmarks on the exact same spec of GCP machine (`c2-standard-8`), and got slightly different results:

```
group                                              contains-performance                   master
-----                                              --------------------                   ------
ilike_utf8 scalar complex                          1.00    305.2±1.28µs        ? ?/sec    1.00    305.7±0.70µs        ? ?/sec
ilike_utf8 scalar contains                         1.11   1685.4±4.02µs        ? ?/sec    1.00   1515.0±8.44µs        ? ?/sec
ilike_utf8 scalar ends with                        1.00    233.9±0.71µs        ? ?/sec    1.00    234.3±0.31µs        ? ?/sec
ilike_utf8 scalar equals                           1.16    248.6±0.28µs        ? ?/sec    1.00    214.2±0.27µs        ? ?/sec
ilike_utf8 scalar starts with                      1.11    279.6±0.95µs        ? ?/sec    1.00    251.2±0.28µs        ? ?/sec
ilike_utf8_scalar_dyn dictionary[10] string[4])    1.00     49.1±0.22µs        ? ?/sec    1.79     88.0±0.15µs        ? ?/sec
like_utf8 scalar complex                           1.00    287.3±1.08µs        ? ?/sec    1.00    288.4±0.90µs        ? ?/sec
like_utf8 scalar contains                          1.23   458.9±11.91µs        ? ?/sec    1.00    373.6±0.36µs        ? ?/sec
like_utf8 scalar ends with                         1.00    234.4±0.21µs        ? ?/sec    1.00    234.3±0.54µs        ? ?/sec
like_utf8 scalar equals                            1.00    217.1±0.20µs        ? ?/sec    1.00    217.1±0.20µs        ? ?/sec
like_utf8 scalar starts with                       1.00    234.4±0.59µs        ? ?/sec    1.08    253.5±0.24µs        ? ?/sec
like_utf8_scalar_dyn dictionary[10] string[4])     1.00     49.0±0.07µs        ? ?/sec    1.80     88.0±0.15µs        ? ?/sec
like_utf8view scalar complex                       1.01    531.2±1.22ms        ? ?/sec    1.00    523.6±3.52ms        ? ?/sec
like_utf8view scalar contains                      1.00    134.6±0.37ms        ? ?/sec    2.97    399.7±0.46ms        ? ?/sec
like_utf8view scalar ends with                     1.01     59.0±0.21ms        ? ?/sec    1.00     58.5±0.12ms        ? ?/sec
like_utf8view scalar equals                        1.03     30.1±0.05ms        ? ?/sec    1.00     29.4±0.09ms        ? ?/sec
like_utf8view scalar starts with                   1.00     54.0±0.12ms        ? ?/sec    1.02     55.2±0.13ms        ? ?/sec
nilike_utf8 scalar complex                         1.00    304.9±0.70µs        ? ?/sec    1.00    305.2±0.59µs        ? ?/sec
nilike_utf8 scalar contains                        1.12   1684.7±5.21µs        ? ?/sec    1.00   1509.5±5.93µs        ? ?/sec
nilike_utf8 scalar ends with                       1.00    234.2±1.14µs        ? ?/sec    1.00    234.2±0.50µs        ? ?/sec
nilike_utf8 scalar equals                          1.16    248.7±0.32µs        ? ?/sec    1.00    214.2±0.43µs        ? ?/sec
nilike_utf8 scalar starts with                     1.11    279.5±0.26µs        ? ?/sec    1.00    251.3±0.47µs        ? ?/sec
nlike_utf8 scalar complex                          1.00    285.8±0.44µs        ? ?/sec    1.01    287.2±0.62µs        ? ?/sec
nlike_utf8 scalar contains                         1.24   461.9±10.51µs        ? ?/sec    1.00    373.9±0.67µs        ? ?/sec
nlike_utf8 scalar ends with                        1.00    234.2±0.20µs        ? ?/sec    1.00    234.3±0.25µs        ? ?/sec
nlike_utf8 scalar equals                           1.00    217.1±0.20µs        ? ?/sec    1.00    217.0±0.25µs        ? ?/sec
nlike_utf8 scalar starts with                      1.00    234.3±0.22µs        ? ?/sec    1.08    253.6±0.36µs        ? ?/sec
```

The only cases which should have changed in this PR are:

```
group                                              contains-performance                   master
-----                                              --------------------                   ------
like_utf8 scalar contains                          1.23   458.9±11.91µs        ? ?/sec    1.00    373.6±0.36µs        ? ?/sec
like_utf8view scalar contains                      1.00    134.6±0.37ms        ? ?/sec    2.97    399.7±0.46ms        ? ?/sec
nlike_utf8 scalar contains                         1.24   461.9±10.51µs        ? ?/sec    1.00    373.9±0.67µs        ? ?/sec
```

I'll try to work out why the first and last are marginally slower with this PR.

**Comment by samuelcolvin** [comment]
The problem here I think is that the haystack length is only [4 characters](https://github.com/apache/arrow-rs/blob/5f5a82cb388094ea2a54f313b5a43249613195aa/arrow/src/util/bench_util.rs#L116)! While of course some haystacks will be that short, I personally don't think that's the only case we should consider.

Running

```bash
cargo bench -p arrow --bench comparison_kernels -F test_utils -- --save-baseline `git rev-parse --abbrev-ref HEAD` '^(like|nlike).*scalar contains'
git checkout contains-performance
cargo bench -p arrow --bench comparison_kernels -F test_utils -- --save-baseline `git rev-parse --abbrev-ref HEAD` '^(like|nlike).*scalar contains'
critcmp master contains-performance
```

With different haystack lengths gives very different results from those shown above:

### With haystack length=10

```
group                            contains-performance                   master
-----                            --------------------                   ------
like_utf8 scalar contains        1.00    375.5±4.54µs        ? ?/sec    2.43    912.8±6.32µs        ? ?/sec
like_utf8view scalar contains    1.00     89.6±1.94ms        ? ?/sec    2.01    179.8±1.80ms        ? ?/sec
nlike_utf8 scalar contains       1.00    374.3±2.67µs        ? ?/sec    2.43    911.1±1.95µs        ? ?/sec
```

### With haystack length=20

```
group                            contains-performance                   master
-----                            --------------------                   ------
like_utf8 scalar contains        1.00    229.6±1.50µs        ? ?/sec    4.46   1024.3±6.95µs        ? ?/sec
like_utf8view scalar contains    1.00     88.9±0.79ms        ? ?/sec    2.07    184.4±2.52ms        ? ?/sec
nlike_utf8 scalar contains       1.00    230.6±3.77µs        ? ?/sec    4.44   1025.1±6.38µs        ? ?/sec
```

### With haystack length=100

```
group                            contains-performance                   master
-----                            --------------------                   ------
like_utf8 scalar contains        1.00    377.3±2.50µs        ? ?/sec    4.51  1701.4±17.41µs        ? ?/sec
like_utf8view scalar contains    1.00     89.4±0.39ms        ? ?/sec    2.02    180.6±2.29ms        ? ?/sec
nlike_utf8 scalar contains       1.00    376.6±1.74µs        ? ?/sec    4.58  1724.9±15.14µs        ? ?/sec
```

### With random haystack length=0..400

**IMHO this is by far the most representative benchmark** (happy to submit a PR to make this change permanent if you agree).

Using the following in `create_string_array_with_len`

```rs
                let length = rng.gen_range(0..max_str_len);
                let value = rng.sample_iter(&Alphanumeric).take(length).collect();
```

```
group                            contains-performance                   master
-----                            --------------------                   ------
like_utf8 scalar contains        1.00   882.0±29.67µs        ? ?/sec    3.33      2.9±0.08ms        ? ?/sec
like_utf8view scalar contains    1.00     89.8±2.13ms        ? ?/sec    2.04    182.9±3.11ms        ? ?/sec
nlike_utf8 scalar contains       1.00   867.1±11.87µs        ? ?/sec    3.39      2.9±0.06ms        ? ?/sec
```

---

These benchmarks were all run on my M3 mac, but that's pretty consistent with the GCP VM. I ran the last benchmark ("With random haystack length=0..400") on GCP to confirm:

```
group                            contains-performance                   master
-----                            --------------------                   ------
like_utf8 scalar contains        1.00  1661.6±16.26µs        ? ?/sec    3.22      5.4±0.02ms        ? ?/sec
like_utf8view scalar contains    1.00    132.4±0.21ms        ? ?/sec    2.92    386.5±0.46ms        ? ?/sec
nlike_utf8 scalar contains       1.00  1659.9±14.95µs        ? ?/sec    3.22      5.3±0.01ms        ? ?/sec
```

---

## Summary

I guess we could do some special casing in the contains logic to use `str.contains` for very short haystacks, but personally I don't think it's worth it — it would make the kernel a bit slower in all cases.

Personally I think this change is good as is and we should update the benchmark code to use more representative haystacks.

LMK what you think.

**Comment by alamb** [comment]
> Personally I think this change is good as is and we should update the benchmark code to use more representative haystacks.


I agree we should update the benchmarks (which we have done in https://github.com/apache/arrow-rs/pull/6147 -- thank you)

I took the liberty of merging up from main with this PR and will rerun the benchmarks just to be sure

**Comment by alamb** [comment]
I am still messing around with benchmarks (I had some problems with my scripts which I have now fixed). I expect results to complete soon

**Review by alamb — APPROVED** [review]
Here is what I got

The ones that have much slower performance like this are measuring in us 
```
like_utf8_scalar_dyn dictionary[10] string[4])     1.81     88.6±0.48µs        ? ?/sec    1.00     49.0±0.15µs        ? ?/sec
```

```
++ critcmp master contains-performance
group                                              contains-performance                   master
-----                                              --------------------                   ------
ilike_utf8 scalar complex                          1.00     23.1±0.13ms        ? ?/sec    1.00     23.2±0.12ms        ? ?/sec
ilike_utf8 scalar contains                         1.00     23.2±0.13ms        ? ?/sec    1.00     23.2±0.12ms        ? ?/sec
ilike_utf8 scalar ends with                        1.00  1448.8±53.50µs        ? ?/sec    1.00  1454.3±76.12µs        ? ?/sec
ilike_utf8 scalar equals                           1.03   875.6±40.43µs        ? ?/sec    1.00   850.7±31.81µs        ? ?/sec
ilike_utf8 scalar starts with                      1.02  1375.2±48.72µs        ? ?/sec    1.00  1353.0±101.91µs        ? ?/sec
ilike_utf8_scalar_dyn dictionary[10] string[4])    1.80     88.8±0.55µs        ? ?/sec    1.00     49.4±0.18µs        ? ?/sec
like_utf8 scalar complex                           1.00     21.9±0.11ms        ? ?/sec    1.00     21.8±0.10ms        ? ?/sec
like_utf8 scalar contains                          1.00  1950.7±47.88µs        ? ?/sec    3.04      5.9±0.07ms        ? ?/sec
like_utf8 scalar ends with                         1.00   671.7±22.93µs        ? ?/sec    1.01   681.4±22.47µs        ? ?/sec
like_utf8 scalar equals                            1.00     91.5±0.38µs        ? ?/sec    1.38    126.3±0.30µs        ? ?/sec
like_utf8 scalar starts with                       1.00   646.0±25.67µs        ? ?/sec    1.02   656.6±18.61µs        ? ?/sec
like_utf8_scalar_dyn dictionary[10] string[4])     1.81     88.6±0.48µs        ? ?/sec    1.00     49.0±0.15µs        ? ?/sec
like_utf8view scalar complex                       1.00    538.0±2.47ms        ? ?/sec    1.01    543.4±3.07ms        ? ?/sec
like_utf8view scalar contains                      1.00    145.0±0.40ms        ? ?/sec    2.92    423.2±0.67ms        ? ?/sec
like_utf8view scalar ends with                     1.01     68.0±0.32ms        ? ?/sec    1.00     67.5±0.35ms        ? ?/sec
like_utf8view scalar equals                        1.07     37.6±0.12ms        ? ?/sec    1.00     35.0±0.20ms        ? ?/sec
like_utf8view scalar starts with                   1.00     67.5±0.20ms        ? ?/sec    1.02     68.9±0.25ms        ? ?/sec
nilike_utf8 scalar complex                         1.01     23.5±0.21ms        ? ?/sec    1.00     23.2±0.13ms        ? ?/sec
nilike_utf8 scalar contains                        1.00     23.3±0.12ms        ? ?/sec    1.00     23.3±0.11ms        ? ?/sec
nilike_utf8 scalar ends with                       1.05  1529.7±70.73µs        ? ?/sec    1.00  1458.9±69.61µs        ? ?/sec
nilike_utf8 scalar equals                          1.06   890.8±41.02µs        ? ?/sec    1.00   841.8±35.16µs        ? ?/sec
nilike_utf8 scalar starts with                     1.11  1521.0±92.20µs        ? ?/sec    1.00  1364.6±52.92µs        ? ?/sec
nlike_utf8 scalar complex                          1.00     21.9±0.03ms        ? ?/sec    1.00     21.8±0.06ms        ? ?/sec
nlike_utf8 scalar contains                         1.00  1914.5±37.92µs        ? ?/sec    3.12      6.0±0.10ms        ? ?/sec
nlike_utf8 scalar ends with                        1.02   675.5±22.54µs        ? ?/sec    1.00   665.5±15.93µs        ? ?/sec
nlike_utf8 scalar equals                           1.00     91.3±0.37µs        ? ?/sec    1.39    126.5±0.53µs        ? ?/sec
nlike_utf8 scalar starts with                      1.03   648.3±26.15µs        ? ?/sec    1.00   628.3±25.21µs        ? ?/sec
```

Thus I think this is good to go.

Thank you @samuelcolvin  for bearing with me on this exercise

**Pull request merged**
