### PR TITLE
Set `default-features = false` for `zstd` in the parquet crate to support `wasm32-unknown-unknown`

### PR DESCRIPTION
**Pull request by kylebarron**
# Which issue does this PR close?

Relevant to #180 but does not fully close it, as LZ4 still does not build on `wasm32-unknown-unknown`.

# Rationale for this change
 
- zstd has released [version 0.11.1](https://github.com/gyscos/zstd-rs/commit/ed00cb511212831d2befd48c2b2150429c85ec98) with Web Assembly (`wasm32-unknown-unknown`) support https://github.com/gyscos/zstd-rs/pull/139.
- This builds for `wasm32-unknown-unknown` only with `default-features = false`

# What changes are included in this PR?

Add `default-features = false` to the zstd dependency.

# Are there any user-facing changes?

None

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]

**Comment by alamb** [comment]
Related: https://github.com/apache/arrow-rs/pull/1415

**Comment by kylebarron** [comment]
I did also have to add `default-features = false` for wasm support, though it looks like we weren't using any default features.

**Comment by kylebarron** [comment]
Version 0.11.0 is missing the shim header files for wasm support. I updated the `Cargo.toml`'s `include` array in https://github.com/gyscos/zstd-rs/pull/145 and that was included in 0.11.1.

Now the parquet crate builds with
```
cargo build --target wasm32-unknown-unknown --no-default-features --features zstd
```
(after adding `getrandom = { version = "0.2.3", features = ["js"] }`, needed for wasm, though usually marked as a dependency by a downstream package).

**Comment by kylebarron** [comment]
I was made aware that bumping to `0.11.1` in `Cargo.toml` might not be necessary, as `cargo update` will choose `0.11.1` automatically. But regardless, wasm support still needs `default-features = false`.

**Comment by alamb** [comment]
> I was made aware that bumping to 0.11.1 in Cargo.toml might not be necessary, as cargo update will choose 0.11.1 automatically. But regardless, wasm support still needs default-features = false.

Putting `0.11.1` in Cargo.toml will ensure that at least `0.11.1` is used (not `0.11.0`, if there is such a thing). I think it is fine to leave in

**Comment by alamb** [comment]
Thanks @kylebarron

**Pull request merged**
