### PR TITLE
Donate `object_store` code from object_store_rs to arrow-rs

### PR DESCRIPTION
**Pull request by alamb**
~Draft until~
- [x] Ensure I can port CI from .circleci https://github.com/influxdata/object_store_rs/pull/51 (will port as a follow on PR)
- [x] IP Clearance: https://github.com/apache/arrow-rs/issues/2096
- [x] Approved on mailing list: https://lists.apache.org/thread/5gfmvlf7lhs6lrcb0l8syq9s6dvs0mo8

# Which issue does this PR close?
re https://github.com/apache/arrow-rs/issues/2030

# Rationale for this change
 
See https://github.com/apache/arrow-rs/issues/2030

# What changes are included in this PR?

These are kept in different commits for easier review:

- [x] Copy in the code from object_store_rs at https://github.com/influxdata/object_store_rs/commit/3c51870ac41a90942c2e45bb499a893d514ed1da
- [x] Update documentation for new home

Follow on Items:
- [ ] Port CI to github actions~ (I propose to do this in a follow on PR -- code is in https://github.com/influxdata/object_store_rs/pull/51)
- [ ] File follow on ticket for ignored `local::tests::bubble_up_io_errors`

# Are there any user-facing changes?
Not yet

### CODE REVIEW

**Comment by alamb** [comment]
Update here: my git-fu is not strong enough to try and keep the history from object_store_rs -- @tustvold  plans to give it a try. In the interim I will work on porting the tests to use github actions

**Comment by tustvold** [comment]
> keep the history from object_store_rs

So unfortunately object_store_rs contains merge commits, so the only way to do this would break the linear history of arrow-rs, either by keeping the merge commits from object_store_rs/main or by adding a single merge commit. I therefore think its not worth it.

**Comment by alamb** [comment]
Update on test migration: 
1. There appears to be one test that needs to be rewritten for github runners https://github.com/apache/arrow-rs/runs/7362535940?check_suite_focus=true (`bubble_up_io_errors`)
2. I have gotten the emulator tests running using github actions here: https://github.com/influxdata/object_store_rs/pull/51 (it needs some polishing but I propose merging this PR first and then adding in object_store tests after the merge

**Comment by tustvold** [comment]
Probably the Github Actions runner is running as root, and therefore the permission failure doesn't occur. I'll rework the test

**Comment by alamb** [comment]
>  Probably the Github Actions runner is running as root, and therefore the permission failure doesn't occur. I'll rework the test

I have `#[ignored]` the test in https://github.com/apache/arrow-rs/pull/2081/commits/ed0f926612adafe40ff0e0fef0eee29dd9e03418 and will file a follow on ticket to fix it

**Pull request merged**
