### PR TITLE
ci: simplify octokit add assignee

### LINKED ISSUE #6279: Simplify take octokit workflow
Following on from https://github.com/apache/arrow-rs/pull/6267#discussion_r1723329758, we should update `take.yml` to use `actions/github-script@v7`.

### PR DESCRIPTION
**Pull request by dsgibbons**
Closes #6279.

Tested using:
- Repo: https://github.com/dsgibbons/test-action
- Issue: https://github.com/dsgibbons/test-action/issues/6
- Workflow run: https://github.com/dsgibbons/test-action/actions/runs/10481567596/job/29031253486

### CODE REVIEW

**Comment by dsgibbons** [comment]
@Xuanwo is this more like what you had in mind?

**Comment by Xuanwo** [comment]
> @Xuanwo is this more like what you had in mind?

Perfect, thank you!

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Review by alamb — APPROVED** [review]
Nice -- thank you @dsgibbons  and @Xuanwo

**Pull request merged**
