### PR TITLE
ARROW-12411: [Rust] Create RecordBatches from Iterators

### LINKED ISSUE #210: Add Builder interface for adding Arrays to record batches
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-12411

Use case:

While writing tests (both in IOx and in DataFusion) where I need a single `RecordBatch`, I often find myself doing something like this:

```
        let schema = Arc::new(Schema::new(vec![
            ArrowField::new("float_field", ArrowDataType::Float64, true),
            ArrowField::new("time", ArrowDataType::Int64, true),
        ]));

        let float_array: ArrayRef = Arc::new(Float64Array::from(vec![10.1, 20.1, 30.1, 40.1]));
        let timestamp_array: ArrayRef = Arc::new(Int64Array::from(vec![1000, 2000, 3000, 4000]));

        let batch = RecordBatch::try_new(schema, vec![float_array, timestamp_array])
            .expect("created new record batch");
```

This is annoying because the information that `float_field` is a float is encoded both in the Schema and the `Float64Array`

I would much rather rather be able to construct RecordBatches a a builder style to avoid the the redundancy and reduce the amount of typing / redundancy:

```

        let float_array: ArrayRef = Arc::new(Float64Array::from(vec![10.1, 20.1, 30.1, 40.1]));
        let timestamp_array: ArrayRef = Arc::new(Int64Array::from(vec![1000, 2000, 3000, 4000]));

        let batch = RecordBatch::empty()
          .append("float_field", timestamp_array).unwrap()
          .append("time", float_array).unwrap;

```

The proposal is to add a method to `RecordBatch` like

```
impl RecordBatch {
...
  fn append(self, field_name: &str, field_values: ArrayRef) -> Result<Self>
}
```

That would append the a field name to the current schema, returning an error if field_name was already present.

The nullability of the field would be set based on the actual null count of the field_values

### PR DESCRIPTION
**Pull request by alamb**
(Here is a PR to the new arrow crate to see what how this process is working!)
Closes #210 

# Rationale / Usecase:

While writing tests (both in IOx and in DataFusion) where I need a single `RecordBatch`, I often find myself doing something like this (copied directly from IOx source code):

```rust
let schema = Arc::new(Schema::new(vec![
    ArrowField::new("float_field", ArrowDataType::Float64, true),
    ArrowField::new("time", ArrowDataType::Int64, true),
]));

let float_array: ArrayRef = Arc::new(Float64Array::from(vec![10.1, 20.1, 30.1, 40.1]));
let timestamp_array: ArrayRef = Arc::new(Int64Array::from(vec![1000, 2000, 3000, 4000]));

let batch = RecordBatch::try_new(schema, vec![float_array, timestamp_array])
    .expect("created new record batch");
```

This is annoying because I have to redundantly (and verbosely) encode the information that `float_field` is a Float64 both in the `Schema` and the `Float64Array`

I would much rather  be able to construct `RecordBatches` using a more Rust like style to avoid the the redundancy and reduce the amount of typing / redundancy:

# Proposed Change
As suggested in the comments from @returnString @nevi-me @jorgecarleitao in the draft PR: https://github.com/apache/arrow/pull/10063 add `try_from_iter` and `try_iter_with_null` functions

```rust
let record_batch = RecordBatch::try_from_iter(vec![
  ("a", Arc::new(a) as ArrayRef),
  ("b", Arc::new(b) as ArrayRef)
]).expect("valid conversion");
```

# TryFrom Implementation

Note I would really like to add a`TryFrom` implementation so I could write

```rust
let record_batch: RecordBatch = vec![
  ("a", Arc::new(a) as ArrayRef),
  ("b", Arc::new(b) as ArrayRef)
].try_into().expect("valid conversion");
```

However, when I tried to do so (with the following):

```rust
impl <I,F> TryFrom<I> for RecordBatch
where
     I: IntoIterator<Item=(F, ArrayRef)>,
     F: AsRef<str>,
{
    type Error = ArrowError;

    fn try_from(value: I) -> std::result::Result<Self, Self::Error> {
        Self::try_from_iter(value)
    }
}
```

I got the following compiler error

```
     = note: conflicting implementation in crate `core`:
            - impl<T, U> TryFrom<U> for T
              where U: Into<T>;

```

Which appears to be a limitation of the Rust typesystem / compiler: See https://github.com/rust-lang/rust/issues/50133. Any help / suggestions from reviewers would be most appreciated.

### CODE REVIEW

**Comment by alamb** [comment]
I rewrote master to remove the history of the other languages (and 50MB of history). This means this PR needs to be "rebased" against the current master.

The best way I found to do this was to find the relevant commits (via `git log`) and then cherry-pick them one at a time. Specifically, for this PR:
```
git reset --hard apache/master
git cherry-pick 5d3c337710b89871a46f6e623bad8c9e05419ed2
git push -f alamb
```

**Comment by jorgecarleitao** [comment]
We had to perform a small re-write of master. The commits may look a bit odd, but it should not cause conflicts. Could you kindly rebase this against the latest master to make it easier to review?

**Comment by alamb** [comment]
fyi @returnString

**Review by returnString — APPROVED** [review]
Nice, looking forward to less ceremony in test cases 👍

**Review by jorgecarleitao — APPROVED** [review]
Sorry, I thought I had approved this, but it was prob. on the old repo. Thanks for the ping.

This looks great, including great documentation and tests! 👍

**Comment by jorgecarleitao** [comment]
fyi, I think that this closes #210 , could you add it to the description so github picks it up?

**Pull request merged**
