### PR TITLE
Remove redundant has_ methods for optional column metadata fields

### LINKED ISSUE #1344: Remove redundant has_ methods for optional column metadata fields
Remove redundant has_ methods for optional column metadata members as they could be access by `if let(Some) = field`.

### PR DESCRIPTION
**Pull request by shanisolomon**
# Which issue does this PR close?

Closes #1344.

# Rationale for this change
 Remove redundant has_ methods for optional column metadata members as they could be access by `if let(Some) = field`.

### CODE REVIEW

**Comment by sunchao** [comment]
This looks fine. I'm just not sure if it'll break some existing code depending on the crate though since they are public.

**Comment by shanisolomon** [comment]
@sunchao IIUC the methods were exposed part of v9.1 which hasn't been published yet?

**Review by sunchao — APPROVED** [review]
Oh I see. Then LGTM.

**Comment by shanisolomon** [comment]
@alamb Do you mind please assisting with merging? :)

**Comment by sunchao** [comment]
Merged, thanks @shanisolomon !

**Comment by alamb** [comment]
Since these functions were released in 9.1.0 removing them is technically a breaking change, so marking them as such

**Pull request merged**
