### PR TITLE
Faster f64 equality

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #.

# Rationale for this change
 

LLVM isn't smart enough to work out that this is just a bitwise equality, so give it a hand - https://rust.godbolt.org/z/347nWGxoW

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by viirya — APPROVED** [review]
I verified that this works for f64::NAN too.

**Review by Dandandan — COMMENTED** [review]
Wouldn't the same apply for `is_ne`?

**Comment by mbrobbel** [comment]
Is this correct? I don't think this is valid for `NaN`: https://github.com/rust-lang/rust/blob/a3c0a023611fcaf5ae3ec242d7d60e356041d25f/library/core/src/num/f64.rs#L426.

**Comment by tustvold** [comment]
@mbrobbel This crate follows the totalOrder predicate as defined in the IEEE 754 (2008 revision) floating point standard, which is different from the default PartialOrd and PartialEq implementations provided by Rust for floating point numbers. Instead using https://doc.rust-lang.org/std/primitive.f32.html#method.total_cmp

**Pull request merged**
