### PR TITLE
Add write method to Json Writer

### LINKED ISSUE #1340: Add `write` method to JsonWriter
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)
I'm looking to add `write_json` functionality in `DataFusion` as part of https://github.com/apache/arrow-datafusion/issues/1777.  Right now `write_csv` and `write_parquet` use a `writer.write(batch)` approach for writing a stream of batches.   The current `JsonWriter` only has `write_batches` which takes a slice of `RecordBatch`es.

**Describe the solution you'd like**
I would like to add a `write` method to the writer which takes only a single `RecordBatch` - similar to the other writers.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by matthewmturner**
# Which issue does this PR close?

Closes #1340 

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
LGTM -- thanks @matthewmturner

**Comment by v1gnesh** [comment]
Hello @alamb and @matthewmturner,

Any comments on how the work in these 2 projects overlaps with work on JSON/Arrow that happens here (in `arrow-rs`):

https://github.com/chmp/serde_arrow
https://github.com/simd-lite/simd-json-derive

**Comment by alamb** [comment]
Hi @v1gnesh  I am not familiar with those crates. This is probably a question better directed at the authors of them (and if there is anything they wanted to contribute back to the arrow crate)

@chmp @Licenser

**Comment by chmp** [comment]
Sure happy to sum up `serde_arrow`. First: at the moment it's only an experiement. I found it useful for some private data processing, and thought maybe it's also helpful to others. At the moment the status is usuable, but only those cases are handled, that I needed so far.

The basic idea is to allow record batches to be used as a "file format" for serde. A typical way of using serde is to take some Rust structs, to implement serialize, and then to generate JSON from these structs. `serde_arrow` allows you to use the same structs, but to generate record batches. So you don't have to use the `arrow` builder API, but can simply derive `serde::Serialize` and then call `serde_arrow::to_record_batch`. The reverse process, reading structs from a record batch is also supported. One complication is, that the data models of `serde` and `arrow` do not match. For that reason `serde_arrow` offers additional logic to let the user specify how to translate the `serde` data model into `arrow` one and back again.

For eaxmple:

```rust
#[derive(Serialize)]
struct Example {
    a: f32,
    b: i32,
}

let examples = vec![
    Example { a: 1.0, b: 1 },
    Example { a: 2.0, b: 2 },
];

let schema = serde_arrow::Schema::from_records(&examples)?;
let batch = serde_arrow::to_record_batch(&examples, schema)?;
```

**Comment by alamb** [comment]
That is interesting -- @chmp  -- I tried to do something similar with IOx (to create RecordBatches from vec's of objects we already had and then expose them as SQL queryable tables)

**Comment by chmp** [comment]
That sound's awesome could you point me to the impl for some inspiration? In case you're interested, I typed up an explanation for how `serde_arrow` works [here](https://github.com/chmp/serde_arrow/blob/main/serde_arrow/Implementation.md).

**Comment by alamb** [comment]
@chmp  this is as far as I got: https://github.com/influxdata/influxdb_iox/issues/1013#issuecomment-806741682

We eventually went with manual conversion to Arrow :
https://github.com/influxdata/influxdb_iox/blob/main/db/src/system_tables.rs

**Comment by chmp** [comment]
Thanks for the link. The code looks actually quite similar. Def. gonna borrow the idea to support iterables directly :)

**Comment by alamb** [comment]
Yeah, I would love a way to support automatically creating arrow arrays from something that implemented `serde` -- so many cool projects to do I just ran out of time ;)

**Pull request merged**
