### PR TITLE
Seal the decimal type.

### LINKED ISSUE #2440: There is no compiler error when using an invalid Decimal type.
**Describe the bug**
Users can create Decimal values with invalid BYTE_WIDTH, such as
```rust
let v = BasicDecimal::<1>::new(1, 1, &[1]);
```

**Expected behavior**
We need to add more restriction to the decimal type so that only `Decimal128` and `Decimal256` can be used.

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
# Which issue does this PR close?

Closes #2440.

# Rationale for this change
The current implementation of `BasicDecimal` cannot restrict the `BYTE_WIDTH` to be 16 or 32, which means that you can create an invalid decimal value like this
```rust
let v = BasicDecimal::<1>::new(1, 1, &[1]);
```

# What changes are included in this PR?
We create a new public trait `ValidDecimal` and implement the trait for `Decimal128` and `Decimal256`. The idea is from https://users.rust-lang.org/t/how-to-seal-the-const-generic/77947/2.
Because of the orphan rule, downstream users cannot implement `ValidDecimal` for other `BasicDecimal` types.

# Are there any user-facing changes?
No breaking.

### CODE REVIEW

**Comment by HaoYang670** [comment]
Hi @tustvold, Could you please help review?

**Comment by HaoYang670** [comment]
@viirya @liukun4515 Could you please help to review?

**Review by tustvold — COMMENTED** [review]
As #2001 hasn't been released yet, I think we have an opportunity to revisit this prior to the next release https://github.com/apache/arrow-rs/issues/2382#issuecomment-1217702351

In particular using a const generic and then constraining it in this way feels a bit derived. Perhaps we could instead have

```
pub trait DecimalType {
    const BYTE_LENGTH: usize;
    const MAX_PRECISION: usize;
    const MAX_SCALE: usize;
    const TYPE_CONSTRUCTOR: fn(usize, usize) -> DataType;
    const DEFAULT_TYPE: DataType;
}

pub struct Decimal128Type {}

pub struct Decimal256Type {}

pub struct DecimalArray<T: DecimalType>
```

**Comment by HaoYang670** [comment]
Hi @tustvold, do you mean that you want to revert https://github.com/apache/arrow-rs/pull/2383?

**Comment by tustvold** [comment]
> Hi @tustvold, do you mean that you want to revert https://github.com/apache/arrow-rs/pull/2383?

I was more wondering if we could build upon it, to polish off some rough edges. Perhaps you could take a look at https://github.com/apache/arrow-rs/pull/2477 and let me know what you think?

**Pull request closed without merging**
