### PR TITLE
use rust edition 2021

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #.
Blocked by https://github.com/apache/arrow/pull/11557
Related #714

# Rationale for this change
 
https://blog.rust-lang.org/2021/05/11/edition-2021.html

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Jimexist** [comment]
Not sure why miri fails

**Comment by alamb** [comment]
I am looking into it on https://github.com/apache/arrow-rs/issues/879

**Comment by Jimexist** [comment]
with @alamb's help this is finally ready. I'm removing the line to ignore the Miri tests

**Review by houqp — APPROVED** [review]

**Comment by alamb** [comment]
🎉

**Pull request merged**
