### PR TITLE
Improve performance of casting `StringView`/`BinaryView` to `DictionaryArray`

### LINKED ISSUE #5861: `cast` kernel support for `StringViewArray` and `BinaryViewArray` `<--> `DictionaryArray`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This is part of the larger project to implement `StringViewArray` -- see https://github.com/apache/arrow-rs/issues/5374

In https://github.com/apache/arrow-rs/issues/5508, @RinChanNOWWW  tracked adding casting to/from StringArray 🙏 ❤️ 

This ticket tracks adding additional data type support for `StringViewArray` and `ByteViewArray` in the `cast` kernel: https://docs.rs/arrow/latest/arrow/compute/kernels/cast/index.html

Many systems (e.g InfluxDB 3.0, Apache DataFusion Comet, and I think Coralogix) use DictionaryArrays. Thus supporting casting to/from `DictionaryArray` will be important to permit easy integration into downstream consumers

**Describe the solution you'd like**

Specifically the following conversions should be supported in the cast kernels:
* `StringViewArray` <--> `DictionaryArray<IndexType, Utf8>`
* `StringViewArray` <--> `DictionaryArray<IndexType, LargeUtf8>`

And similarly for `Binary`:
* `BinaryViewArray` <--> `DictionaryArray<IndexType, Binary>`
* `BinaryViewArray` <--> `DictionaryArray<IndexType, LargeBinary>`

Notes: 
1. Good test coverage is the most important part of this ticket
2. I recommend smaller PRs if possible
3. I think `DictionaryArray<IndexType, LargeUtf8>` --> `StringViewArray` can be implemented without copying strings
3. I think `StringViewArray` --> `DictionaryArray<IndexType, LargeUtf8>` will likely require copying the strings

**Describe alternatives you've considered**
I think casting from Dictionary 

**Additional context**

### PR DESCRIPTION
**Pull request by XiangpengHao**
# Which issue does this PR close?

Closes #5861 . This pr should only be reviewed/merged after #5871 is merged.

# Rationale for this change
 Cast view types to dictionary arrays, the opposite of https://github.com/apache/arrow-rs/pull/5871

Note that casting was handled by pack_byte_to_dictionary:
https://github.com/XiangpengHao/arrow-rs/blob/dict-to-view/arrow-cast/src/cast/dictionary.rs#L307

But it takes two steps: Utf8View -> Utf8 -> Dictionary, which causes two copies.
This PR only do one copy (directly from Utf8View -> Dictionary<>)

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you @XiangpengHao  -- 

Since the rationale for these changes is performance, I think we should have benchmark results showing how much faster it is.

Thus, can you please make a PR with a banchmark (a single PR with benchmarks both for this change and the one in https://github.com/apache/arrow-rs/pull/5871)

Then we'll use the benchmarks to  verify that this PR really does improve performance (I am sure it will, but we should double check)

**Comment by alamb** [comment]
I took the liberty of merging this PR up from main. Running performance benchmarks on it now

**Review by alamb — APPROVED** [review]
I measure a 30% performance improvement on this branch. Thank you @XiangpengHao 

```
++ critcmp master dict-to-view
group                       dict-to-view                           master
-----                       ------------                           ------
cast dict to string view    1.00     69.0±2.58µs        ? ?/sec    1.02    70.6±12.48µs        ? ?/sec
cast string view to dict    1.00    203.3±0.32µs        ? ?/sec    1.34    272.1±0.69µs        ? ?/sec
```

**Comment by XiangpengHao** [comment]
> Does this PR close #5861 I wonder 🤔

I guess it should. Are there any remaining items?

**Comment by alamb** [comment]
> I guess it should. Are there any remaining items?

Not that I know of

**Comment by alamb** [comment]
🚀

**Pull request merged**
