### PR TITLE
fix bug: error type for BufferBuilder

### LINKED ISSUE #1103: Error BufferBuilder type
**Describe the bug**

In definition of `BufferBuilder` is
```
pub struct BufferBuilder<T: ArrowNativeType> 
```

If we want to define a new type of BufferBuilder, the T is must be ArrowNativeType.

But in some definitions, the T is ArrowPrimitiveType.

```
pub type TimestampSecondBufferBuilder = BufferBuilder<TimestampSecondType>;
pub type TimestampMillisecondBufferBuilder = BufferBuilder<TimestampMillisecondType>;
pub type TimestampMicrosecondBufferBuilder = BufferBuilder<TimestampMicrosecondType>;
pub type TimestampNanosecondBufferBuilder = BufferBuilder<TimestampNanosecondType>;
pub type Date32BufferBuilder = BufferBuilder<Date32Type>;
pub type Date64BufferBuilder = BufferBuilder<Date64Type>;
pub type Time32SecondBufferBuilder = BufferBuilder<Time32SecondType>;
pub type Time32MillisecondBufferBuilder = BufferBuilder<Time32MillisecondType>;
pub type Time64MicrosecondBufferBuilder = BufferBuilder<Time64MicrosecondType>;
pub type Time64NanosecondBufferBuilder = BufferBuilder<Time64NanosecondType>;
pub type IntervalYearMonthBufferBuilder = BufferBuilder<IntervalYearMonthType>;
pub type IntervalDayTimeBufferBuilder = BufferBuilder<IntervalDayTimeType>;
pub type IntervalMonthDayNanoBufferBuilder = BufferBuilder<IntervalMonthDayNanoType>;
pub type DurationSecondBufferBuilder = BufferBuilder<DurationSecondType>;
pub type DurationMillisecondBufferBuilder = BufferBuilder<DurationMillisecondType>;
pub type DurationMicrosecondBufferBuilder = BufferBuilder<DurationMicrosecondType>;
pub type DurationNanosecondBufferBuilder = BufferBuilder<DurationNanosecondType>;
```

**To Reproduce**

**Expected behavior**

**Additional context**

We need to fix it by using `ArrowPrimitiveType::Native`

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #1103 

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by liukun4515** [comment]
@alamb  PTAL

**Review by alamb — COMMENTED** [review]
This change looks fine to me but I don't fully understand the need for it. Is there any behavior change after the changes in this PR?

Or put another way, is there something you plan to do that you can't do without the changes in this PR?

**Comment by liukun4515** [comment]
> This change looks fine to me but I don't fully understand the need for it. Is there any behavior change after the changes in this PR?
> 
> Or put another way, is there something you plan to do that you can't do without the changes in this PR?

If we use the original code, I can't create a  `TimestampSecondBufferBuilder`.
I think it's an error or bug.

**Comment by liukun4515** [comment]
We will meet the error If we don't do these changes.
```
error[E0599]: the function or associated item `new` exists for struct `builder::BufferBuilder<datatypes::types::TimestampSecondType>`, but its trait bounds were not satisfied
   --> arrow/src/array/mod.rs:507:39
    |
507 |         TimestampSecondBufferBuilder::new(10);
    |                                       ^^^ function or associated item cannot be called on `builder::BufferBuilder<datatypes::types::TimestampSecondType>` due to unsatisfied trait bounds
    |
   ::: arrow/src/array/builder.rs:83:1
    |
83  | pub struct BufferBuilder<T: ArrowNativeType> {
    | -------------------------------------------- function or associated item `new` not found for this
    |
   ::: arrow/src/datatypes/types.rs:32:9
    |
32  |         pub struct $name {}
    |         ---------------- doesn't satisfy `_: native::ArrowNativeType`
    |
    = note: the following trait bounds were not satisfied:
            `datatypes::types::TimestampSecondType: native::ArrowNativeType`
note: the following trait must be implemented
   --> arrow/src/datatypes/native.rs:31:1
    |
31  | / pub trait ArrowNativeType:
32  | |     std::fmt::Debug
33  | |     + Send
34  | |     + Sync
...   |
75  | |     }
76  | | }
    | |_^

```

@alamb

**Comment by liukun4515** [comment]
Thanks for your review.

**Pull request merged**
