### PR TITLE
Add ability to reuse `Rows` in encoder

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-rs/issues/4479

# Rationale for this change

When converting many (many!) record batches I would like to avoid the overhead of allocating / zeroing out temporary allocations.  See https://github.com/apache/arrow-rs/issues/4479 for more details

# What changes are included in this PR?

Add `RowConverter::set_target` API to reuse an existing `Rows` when calling `RowConverter:: convert_columns`

If this is an acceptable API I will write some tests

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
Do you have any benchmarks for this

**Comment by alamb** [comment]
> Do you have any benchmarks for this

I do not, but I will create some

**Comment by alamb** [comment]
> Edit: I also wonder if being able to append to an existing rows might be a more flexible API (I will have a play tomorrow)

For DataFusion we would also need a way to 'clear' an existing `Rows`

**Comment by alamb** [comment]
Will return to this after some profiling results

**Pull request closed without merging**
