### PR TITLE
fix: clippy warnings from nightly rust 1.82

### PR DESCRIPTION
**Pull request by waynexia**
# Which issue does this PR close?

Closes #.

# Rationale for this change
 

Find those warnings when working with nightly toolchain in #6336

# What changes are included in this PR?

Fix new clippy warnings.

One rule I didn't touch is [`too_long_first_doc_paragraph`](https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph). This does make sense in some scenarios but lots of the reported doc comment have a long first sentence... 🙈 

# Are there any user-facing changes?

No

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Comment by Xuanwo** [comment]
> One rule I didn't touch is [`too_long_first_doc_paragraph`](https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph). This does make sense in some scenarios but lots of the reported doc comment have a long first sentence... 🙈

I remembered that `cargo fmt` can format them while in nightly.

**Comment by waynexia** [comment]
> > One rule I didn't touch is [`too_long_first_doc_paragraph`](https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph). This does make sense in some scenarios but lots of the reported doc comment have a long first sentence... 🙈
> 
> I remembered that `cargo fmt` can format them while in nightly.

Not in this case. I guess it's not a simple format problem but we need to rephase some sentences. I'd give it a try in a seperated follow-up PR (I tried a few cases and it turns out to be a not very trivial change...)

**Review by crepererum — APPROVED** [review]
thanks

**Pull request merged**
