### PR TITLE
Fix support for ECS IAM credentials

### LINKED ISSUE #4301: [Question - object_store] AWS credentials provider
**Which part is this question about**
`object_store` crate.

**Describe your question**
The `AmazonS3Builder` implements its own AWS credentials resolution and provisioning (which currently doesn't support ECS environments natively).
AWS SDKs (see [here](https://github.com/awslabs/aws-sdk-rust/blob/d1962fd42d376c5c695877041d2a269fd1fa50cd/sdk/aws-config/src/default_provider/credentials.rs#L25) for the Rust SDK) feature a well defined Credential Provider Chain.

My question is: why does this project not use the official AWS Rust SDK implementation for credentials (and possibly the S3 client implementation)?

**Additional context**

Issue #4283 should fix credentials resolution for ECS runtime environments. However the fix doesn't work, since the provided metadata_endpoint is still used in the context of the EC2 credentials provider which postfixes a `/latest/api/token` path, which breaks credentials resolution for ECS: https://github.com/apache/arrow-rs/blob/77aa8f5b2645a91724048f5c1d644c6b52880028/object_store/src/aws/credential.rs#L429

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4301

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
Perhaps @jfuechsl you might be able to give this a test, I don't have access to an ECS cluster

**Comment by jfuechsl** [comment]
Happy to do so. I will report back (should be possible this week).

**Comment by jfuechsl** [comment]
I successfully tested the fix with the following configurations:
1. ECS Fargate
2. ECS EC2 (bridge network mode)
3. ECS EC2 (awsvpc network mode)

Thanks for this fix!

**Review by alamb — APPROVED** [review]
makes sense to me and the fact that we haev a test in the field that verifies it works (thanks @jfuechsl  ) let's :shipit:

**Pull request merged**
