### PR TITLE
Update version to 28.0.0 and add changelog

### PR DESCRIPTION
**Pull request by iajoiner**
# Which issue does this PR close?

re https://github.com/apache/arrow-rs/issues/3118
# Rationale for this change

release
# What changes are included in this PR?

Update version to 28.0.0 and add changelog

See rendered changelog here: https://github.com/spaceandtimelabs/arrow-rs/blob/prepare_for_28.0.0/CHANGELOG.md
# Are there any user-facing changes?

Update version to 28.0.0 and changelog

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @iajoiner  --  I found https://github.com/apache/arrow-rs/pull/3148 is definitely an API change so I confirm 28.0.0 is the right number

**Comment by alamb** [comment]
I have a few more updates to make, but since I can't push commits to this particular branch, I will make a follow on PR to get the most recent updates

**Review by alamb — APPROVED** [review]
Thanks @iajoiner

**Comment by iajoiner** [comment]
@alamb Oh? Maybe we can use my own personal fork for this purpose from now on if it helps.

**Pull request merged**
