### PR TITLE
Benchmark for casting view to dict arrays (and the reverse)

### PR DESCRIPTION
**Pull request by XiangpengHao**
# Which issue does this PR close?

Part of  #5861 .

# Rationale for this change
 Setup a benchmark and see what the performance look like for casting between view and dict arrays.

Related: #5871 #5872

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — DISMISSED** [review]
Thanks @XiangpengHao -- can you please add this benchmark to the existing cast kernel benchmarks rather than its own bench: https://github.com/apache/arrow-rs/blob/master/arrow/benches/cast_kernels.rs ?

(🤔  maybe we should move that cast_kernels.rs benchmark to `arrow-cast/benchmarks` )

**Comment by XiangpengHao** [comment]
> Thanks @XiangpengHao -- can you please add this benchmark to the existing cast kernel benchmarks rather than its own bench: https://github.com/apache/arrow-rs/blob/master/arrow/benches/cast_kernels.rs ?
> 
> (🤔 maybe we should move that cast_kernels.rs benchmark to `arrow-cast/benchmarks` )

Done.

The `cast_kernel.rs` can't be moved to `arrow-cast/benches` because it depends `create_primitive_array` and `seedable_rng` which are currently in `arrow` directory.

**Review by alamb — APPROVED** [review]
Thanks @XiangpengHao

**Comment by alamb** [comment]
🚀 

Merging this in so we can compare performace of main to the specialized cast kernels

**Pull request merged**
