### PR TITLE
Fix arrow-json writer empty

### LINKED ISSUE #6613: Array writer output empty when no record is written
**Describe the bug**

Array writer output is empty when no record is written.
Either when no batch or only empty batches are written the output is empty.
It's ok for line delimiter format but not for array format.

**To Reproduce**
```rust
let mut writer = ArrayWriter::new(vec![] as Vec<u8>);
writer.finish().unwrap();
```

**Expected behavior**

The buffer should contain be a valid json array `[]`, instead it is empty.

### PR DESCRIPTION
**Pull request by gwik**
The Writer output with the ArrayJson formatter was empty when no record were in the output (no write or empty batch write). It should output an empty JSON array `[]` instead.

Closes #6613

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
Thank you

**Comment by jackkleeman** [comment]
Hey folks, I'm not sure if this should have gone out as a minor release, as it will break anyone who assumes that there is no output if there were no rows. We were working around the lack of output by adding the [] ourselves. Super glad we don't have to do that any more, but sadly Cargo automatically bumped the minor version and now we see `[][]` :D

**Comment by tustvold** [comment]
Apologies that this broke your workflow, I viewed this a bug fix and therefore it was appropriate to roll out in a non-breaking release.

**Comment by jackkleeman** [comment]
ok, makes sense to me!

**Comment by jackkleeman** [comment]
https://xkcd.com/1172/

**Pull request merged**
