### PR TITLE
Not reexport RecordBatch twice

### PR DESCRIPTION
**Pull request by lewiszlw**
# Which issue does this PR close?

There are two duplicated reexports with different path. But actually they point to the same source.
image

After this pr,
image

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
This is for backwards compatibility, what is the issue with this?

**Comment by lewiszlw** [comment]
Just a little confused.

**Comment by tustvold** [comment]
Prior to splitting apart the crate RecordBatch lived under arrow::record_batch, it was then moved to live under arrow_array and therefore re-exported under arrow::array. To avoid breaking downstreams an export at the old path was preserved

**Comment by lewiszlw** [comment]
Understand, we might add deprecation info, but feel free to close this pr if you don't think we need this.

**Comment by tustvold** [comment]
I think this isn't worth the downstream churn, but thank you for raising this

**Pull request closed without merging**
