### PR TITLE
Move JSON Test Format To integration-testing

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Part of https://github.com/apache/arrow-rs/issues/2594
Part of https://github.com/apache/arrow-rs/issues/2300
Related to #2723

# Rationale for this change
 

Collocates the code related to the integration tests, reducing coupling to serde_json, potentially improves compilation times.

# What changes are included in this PR?

Follow on to https://github.com/apache/arrow-rs/pull/2598, this moves the JSON schema parsing logic to integration-testing. I had incorrectly assumed this was a canonical representation, however, it is a custom format specific to these tests - https://github.com/apache/arrow/blob/master/docs/source/format/Integration.rst#json-test-data-format. I therefore think it can be safely moved to live alongside the other logic.

# Are there any user-facing changes?

Yes, these APIs were public, but I'm fairly confident they weren't in use, especially as the logic to actually parse the files themselves along with the array data, is not public.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
The idea makes sense to me -- I only worry that someone perhaps was using the JSON serialization code for some other purpose.

If this turns out to be the case, we can always extract the schema parsing code into its own crate as well.

Thanks @tustvold 

 cc @nevi-me  and @viirya

**Review by viirya — COMMENTED** [review]
Looks good. The json format should be for integration test purpose. Although I think it may be possible like @alamb said that it is used for other purpose as it is public now, it is out of the design of the format and we can do extraction later if it is really needed.

**Comment by domoritz** [comment]
I was using the JSON format for schemas in https://github.com/domoritz/csv2parquet. Could you provide a crate for reading/writing schemas from JSON? I don't need the same format.

**Comment by tustvold** [comment]
@domoritz The schema types implement serde::Serialize and Deserialize, and can therefore be used directly with serde_json. Would that be workable?

**Comment by domoritz** [comment]
That should probably work. Do you have a code snippet I could look at?

**Comment by domoritz** [comment]
Perfect. That works!

**Comment by maxburke** [comment]
@alamb was right, someone (my company) was using this code, and now we're broken when trying to move beyond arrow 22

**Comment by maxburke** [comment]
Is it possible to undo this MR and release it as Arrow 24.0.1?

**Comment by alamb** [comment]
Based on some discussions, I think the plan is that @tustvold was going to extract this code into its own crate for reuse. 

I also believe @tustvold  is out for a few days so I would expect a delayed response. Please let me know if it would be helpful to file a ticket for this issue

**Pull request merged**
