### PR TITLE
Use `total_cmp` for floating value ordering and remove `nan_ordering` feature flag

### LINKED ISSUE #2613: Use `total_cmp` for floating value ordering and remove `nan_ordering` feature flag
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

As discussed in #2568, we should use `total_cmp` for floating value ordering and remove `nan_ordering` feature flag.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #2613.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
Could you perhaps run the benchmarks just to see what performance impact this has?

**Comment by viirya** [comment]
Sure. I'll run the benchmark.

**Comment by viirya** [comment]
Ran the comparison benchmarks. No performance difference shown.

**Comment by tustvold** [comment]
> No performance difference shown.

Even when the nan_ordering feature is enabled?

**Comment by viirya** [comment]
> Even when the nan_ordering feature is enabled?

Yes.

**Comment by viirya** [comment]
Thanks @tustvold

**Pull request merged**
