### PR TITLE
Split out value selection kernels into arrow-select (#2594)

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Part of #2594

# Rationale for this change
 

See ticket

# What changes are included in this PR?

Splits out the various value selection kernels into an arrow-select crate

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by tustvold** [comment]
Waiting on #2887 and #2886

**Review by alamb — COMMENTED** [review]
Perhaps I am being naive and selfish (as there is some overhead to making new crates and then the biweekly publishing of them) but is it really necessary to make an entire new crate for 400 lines of rust code?

**Review by alamb — APPROVED** [review]
I think github was rendered the diff slightly confusingly -- moving this code (several thousands of lines) into its own crate sounds good

**Comment by tustvold** [comment]
Yeah GitHub has recently gotten a lot better at understanding file renames

**Pull request merged**
