### PR TITLE
Filter pushdown

### PR DESCRIPTION
**Pull request by thinkharderdev**
# Which issue does this PR close?

Closes #.

# Rationale for this change
 

Add filter pushdown for parquet async reader. This should enable push down of row-level filter predicates to the parquet decoder allowing us to avoid decoding overhead as well as (with some other tweaks) IO overhead when we have page index. 

This will need quite a bit more spit and polish but wanted to get feedback on the basic API

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by thinkharderdev** [comment]
@tustvold @Ted-Jiang

**Comment by tustvold** [comment]
Thank you for this, I intend to explore the design space for this a bit this afternoon and report back. My main concern is being able to handle this in the sync part of the codebase, as this will both likely be simpler, but also benefit both APIs.

**Comment by tustvold** [comment]
> I intend to explore the design space for this a bit this afternoon and report back

Made reasonable progress on this, I intend to polish this up and push up a draft tomorrow

**Comment by tustvold** [comment]
I think this can be closed now?

**Pull request closed without merging**
