### PR TITLE
Add slice support for `Rows` struct

### PR DESCRIPTION
**Pull request by mustafasrepo**
# Which issue does this PR close?

Closes #.

# Rationale for this change
 `Rows` struct is a row representation of the some of the columns in a `RecordBatch`. This is generally used to compare rows in more optimized way. For instance, when a `RecordBatch` is converted to the `Rows`. They will have same number of rows and `Rows.row(idx)` API will return the row `idx` in the original `RecordBatch` (or subset of the columns depends on the construction).

I am working on the Checkpointing using Datafusion. In my use case, I sometimes use a slice of the `RecordBatch`. To be able to keep `Rows`, `RecordBatch` in sync. I need to have `.slice` support for `Rows` struct also (Similar to `RecordBatch`). 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by ozankabak** [comment]
cc @alamb other Datafusion users will probably need this at some point as well so you may want to take a quick look too

**Comment by tustvold** [comment]
See https://github.com/apache/arrow-rs/pull/4817 for prior art in this area.

My concern with this as implemented is it performs a deep-copy of all the data, which is perhaps surprising for users accustomed to array slicing which does not.

One option would be to introduce something like `RowCursor` which combines an `Arc<Rows>` with an offset and length. Provided this implemented `IntoIterator<Item = Row<'a>>` it would be compatible with most row APIs.

It may even be possible such a construct already exists in DataFusion

**Comment by ozankabak** [comment]
Thanks for the feedback, I agree with your concern. I will discuss your suggestions with @mustafasrepo to see if it works for his use case and we will circle back. We will also double check to see if something like this already exists in DF that we might have missed.

**Comment by mustafasrepo** [comment]
> See #4817 for prior art in this area.
> 
> My concern with this as implemented is it performs a deep-copy of all the data, which is perhaps surprising for users accustomed to array slicing which does not.
> 
> One option would be to introduce something like `RowCursor` which combines an `Arc<Rows>` with an offset and length. Provided this implemented `IntoIterator<Item = Row<'a>>` it would be compatible with most row APIs.
> 
> It may even be possible such a construct already exists in DataFusion

@tustvold Thanks. For the suggestion. I could solve the problem with your suggested approach. Closing this PR, since this is now unnecessary.

**Pull request closed without merging**
