### PR TITLE
feat: Initial ORC file format support - WIP

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Relates to https://github.com/apache/arrow-rs/issues/4980

# Rationale for this change
 

Initial support for reading ORC files

# What changes are included in this PR?

New synchronous reader of ORC files which implements RecordBatch iterator

Supported datatypes:

- Smallint
- Int
- Bigint
- Float
- Double
- String
- Char
- Varchar
- Boolean
- Tinyint
- Binary
- Date

Unsupported:

- Decimal
- Timestamps
- Compound types (nested struct, list, map, union)

Currently does simple read of ORC files into RecordBatches, no filtering support. But does support top level projection.

Supports all compression: None, zlib, snappy, lzo, lz4, zstd (delegates to other rust crates for actual decompression)

# Are there any user-facing changes?

New crate

### CODE REVIEW

**Comment by Jefffrey** [comment]
I've marked it as WIP, but I mainly intend to clean up the code a bit, do more tests and improve docs for now

**Comment by alamb** [comment]
> Could we perhaps split this into smaller pieces of less than 1000 lines a go?

Maybe we could start with the basic scaffolding for the arrow-orc crate (and CI checks, etc) and move on from there

**Comment by Jefffrey** [comment]
I've tried splitting it into a more initial version. To note that the proto stuff (file and generated rust) does make up about 1.2k of the 2.4k total lines changed, but can cut down more if desirable

@alamb @tustvold

**Comment by alamb** [comment]
Hi @Jefffrey  -- thanks for the ping. I don't think I am going to have time to review this PR for a while unfortunately

**Comment by alamb** [comment]
I left a comment about review capacity here: https://github.com/apache/arrow-rs/issues/4980#issuecomment-1786897884

**Comment by Jefffrey** [comment]
Following discussion in #4980, will focus on implementing ORC file format support in https://github.com/datafusion-contrib/datafusion-orc with aim of eventually bringing into `arrow-rs` in the future once it's more feature complete. Closing this PR

**Pull request closed without merging**
