### PR TITLE
Check the length of `null_bit_buffer` in `ArrayData::try_new()`

### LINKED ISSUE #1707: `ArrayData::try_new` cannot always return expected error.
Find the bug when working on #911.

**To Reproduce**
Just do a small change on https://github.com/apache/arrow-rs/blob/master/arrow/src/array/data.rs#L1734-L1750
Set `null_count` to be `None` instead of `Some(0)`
```rust
    #[test]
    #[should_panic(expected = "null_bit_buffer size too small. got 1 needed 2")]
    fn test_bitmap_too_small() {
        let buffer = make_i32_buffer(9);
        let null_bit_buffer = Buffer::from(vec![0b11111111]);

        ArrayData::try_new(
            DataType::Int32,
            9,
            None,
            Some(null_bit_buffer),
            0,
            vec![buffer],
            vec![],
        )
        .unwrap();
    }
```

This test will panic at `"range end index 2 out of range for slice of length 1"`.

**Expected behavior**
Panic at `null_bit_buffer size too small. got 1 needed 2`

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

Closes #1707.

# Rationale for this change
The `ArrayData::try_new` will panic if `null_bit_buffer` is too short.

# What changes are included in this PR?
Check the length of `null_bit_buffer` before we call `new_unchecked` in `ArrayData::try_new()`

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by HaoYang670** [comment]
I am not sure if this can be removed: https://github.com/apache/arrow-rs/blob/master/arrow/src/array/data.rs#L683-L693
as `validate()` is a public function.

But if we don't, we will check the length of `null_bit_buffer` twice.

**Review by tustvold — APPROVED** [review]
LGTM, thank you :+1:

**Comment by HaoYang670** [comment]
> But if we don't, we will check the length of `null_bit_buffer` twice.

Maybe in the long term, we should try to remove the `null_count` field from `ArrayData`. I don't find why we need this field except making `fn null_count()` as a `const` function (Who will call `null_count()` multiple times on same array?).

**Comment by tustvold** [comment]
> we should try to remove the null_count field from ArrayData

Often faster kernel implementations are possible if one can ignore nulls, as such null_count helps to inform this selection. It is also fairly common for a given array to be fed to more than one kernel, e.g. cmp then filter, and as such caching the null count on ArrayData avoids computing it multiple times

**Comment by HaoYang670** [comment]
Thank you for your explanation @tustvold. I will do some experiments to test how much performance `null_count` could contribute.

**Review by viirya — APPROVED** [review]
Looks good. Thanks @HaoYang670

**Pull request merged**
