### PR TITLE
chore: export fn parquet_to_array_schema_and_fields

### LINKED ISSUE #4298: export function parquet_to_array_schema_and_fields
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We want to use some low-level APIs to read parquet files by rowgroup (such as `build_array_reader`), but this function need `field: Option<&ParquetField>` that can only constructed by `parquet_to_array_schema_and_fields`.

**Describe the solution you'd like**

Export function `parquet_to_array_schema_and_fields `

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by sundy-li**
# Which issue does this PR close?

Closes #4298

# Rationale for this change
 

# What changes are included in this PR?

1. export fn parquet_to_array_schema_and_fields
2. export ParquetField, ParquetFieldType
3. export trait RowGroupCollection

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
I'm a little apprehensive about exposing these APIs, they are fairly low-level and not really designed to be part of the public API surface. The issue states

> We want to use some low-level APIs to read parquet files by rowgroup 

The higher-level APIs support [filtering by row group](https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ArrowReaderBuilder.html#method.with_row_groups), among other things. Is there a particular piece of functionality that is missing from this?

**Comment by sundy-li** [comment]
Because we don't need the high-level api to read the metadata. The metadata is stored outside parquet files in our database system. Once the metadata and rowgroup index are reader,  rowgroups are pruned and we only need to read the data by row-group with Bytes of each column.

**Comment by tustvold** [comment]
You can override how metadata is loaded by providing a custom AsynFileReader? Is this insufficient?

**Comment by sundy-li** [comment]
Yes, `AsyncFileReader`'s `get_metadata` can work. 

But:
1. We don't store the whole metadata of the parquet files, we just store the `Vec<ColumnChunkMetaData>` of each leaf column, because we only write one row group, so it's much simple and small metadata.
2. The `ParquetRecordBatchStream` will be reading IO task in dedicated async runtime and decoding in blocking threads. But we have completely separated the two processes, we will first fetch the Bytes in dedicated async runtime and send the results to a thread pool to decode them into arrrays.

**Review by tustvold — COMMENTED** [review]
Makes sense, I'll take a look this afternoon to see what we can expose for this use-case. I think we can definitely expose ArrayReader and friends as a stable API, I just want to take the time to make sure we aren't exposing more than we need to

**Comment by sundy-li** [comment]
Thanks, we'd like that arrow-rs could expose some api to cover this method. 

https://github.com/datafuselabs/databend/blob/529d184808eecbf1cd09ce31f3629553478f8ef2/src/query/storages/fuse/src/io/read/block/block_reader_parquet_deserialize.rs#L86-L172

**Pull request closed without merging**
