### PR TITLE
Add get_config_value to AWS/Azure/GCP Builders

### LINKED ISSUE #4021: object_store: Builders (S3/Azure/GCS) are missing the `get method` to get the actual configuration information
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The current Builders (S3/Azure/GCS) only provide the `set method`, e.g. `builder.with_access_key_id()`. 

Since the current Builders also support getting configuration information from the `::from_env()`, so we also need the `get method` to verify that the actual configuration is as expected.

**Describe the solution you'd like**

- support `get method`

**Describe alternatives you've considered**

- make struct fields of builders to `pub`

**Additional context**

### PR DESCRIPTION
**Pull request by r4ntix**
# Which issue does this PR close?

Closes #4021 

# Rationale for this change
 

See #4021 

# What changes are included in this PR?

- make struct fields of `AmazonS3Builder`, `MicrosoftAzureBuilder`, `GoogleCloudStorageBuilder` to pub

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
Would it work to instead provide a method to get values by config key? Exposing the internals of these structs is problematic from the perspective of being able to make changes without breaking API compatibility

**Comment by r4ntix** [comment]
> Would it work to instead provide a method to get values by config key? Exposing the internals of these structs is problematic from the perspective of being able to make changes without breaking API compatibility

@tustvold thanks for the feedback.

Do you mean providing a function like `try_with_option` to convert the config value back to `String` again? 
I have considered code such as:
```rust
pub fn get_config_value(&self, key: impl AsRef<str>) -> Result<Option<String>> {
        let value = match AmazonS3ConfigKey::from_str(key.as_ref())? {
            AmazonS3ConfigKey::AccessKeyId => self.access_key_id.clone(),
            AmazonS3ConfigKey::SecretAccessKey => self.secret_access_key.clone(),
            AmazonS3ConfigKey::Region | AmazonS3ConfigKey::DefaultRegion => {
                self.region.clone()
            }
            AmazonS3ConfigKey::Bucket => self.bucket_name.clone(),
            AmazonS3ConfigKey::Endpoint => self.endpoint.clone(),
            AmazonS3ConfigKey::Token => self.token.clone(),
            AmazonS3ConfigKey::ImdsV1Fallback => Some(self.imdsv1_fallback.to_string()),
            AmazonS3ConfigKey::VirtualHostedStyleRequest => {
                Some(self.virtual_hosted_style_request.to_string())
            }
            AmazonS3ConfigKey::MetadataEndpoint => self.metadata_endpoint.clone(),
            AmazonS3ConfigKey::Profile => self.profile.clone(),
            AmazonS3ConfigKey::UnsignedPayload => Some(self.unsigned_payload.to_string()),
            AmazonS3ConfigKey::Checksum => Some(self.checksum_algorithm.to_string()),
        };
        Ok(value)
    }
```

**Comment by tustvold** [comment]
Or possibly even

```
pub fn get_config_value(&self, key: &AmazonS3ConfigKey) -> Option<String> {
        match key {
            AmazonS3ConfigKey::AccessKeyId => self.access_key_id.clone(),
            AmazonS3ConfigKey::SecretAccessKey => self.secret_access_key.clone(),
            AmazonS3ConfigKey::Region | AmazonS3ConfigKey::DefaultRegion => {
                self.region.clone()
            }
            AmazonS3ConfigKey::Bucket => self.bucket_name.clone(),
            AmazonS3ConfigKey::Endpoint => self.endpoint.clone(),
            AmazonS3ConfigKey::Token => self.token.clone(),
            AmazonS3ConfigKey::ImdsV1Fallback => Some(self.imdsv1_fallback.to_string()),
            AmazonS3ConfigKey::VirtualHostedStyleRequest => {
                Some(self.virtual_hosted_style_request.to_string())
            }
            AmazonS3ConfigKey::MetadataEndpoint => self.metadata_endpoint.clone(),
            AmazonS3ConfigKey::Profile => self.profile.clone(),
            AmazonS3ConfigKey::UnsignedPayload => Some(self.unsigned_payload.to_string()),
            AmazonS3ConfigKey::Checksum => Some(self.checksum_algorithm.to_string()),
        }
    }
```

**Comment by r4ntix** [comment]
@tustvold If we don't consider the consistency of value types, this is a better solution. I will submit a new commit for this, thanks.

**Comment by r4ntix** [comment]
I have submitted a new commit, use `get_config_value` method instead of public fields.

**Review by tustvold — APPROVED** [review]
LGTM, thank you

**Pull request merged**
