### PR TITLE
Test case which shows empty list of struct cannot be written

### PR DESCRIPTION
**Pull request by mosyp**
# Which issue does this PR close?
Shows the simple repro steps for #703

# What changes are included in this PR?
 Just a test case

### CODE REVIEW

**Comment by alamb** [comment]
I wonder if https://github.com/apache/arrow-rs/pull/692 could be related. It is also in parquet and affects a similar sounding part of the codebase

**Comment by nevi-me** [comment]
> I wonder if #692 could be related. It is also in parquet and affects a similar sounding part of the codebase

It's unrelated @alamb. The bug is with how levels of `<list<struct<_>>` are calculated.

@mosyp I'll pick this PR up for the test case when I submit a PR that fixes the underlying issue.

**Comment by nevi-me** [comment]
I have a potential fix for this, where this test case no longer fails, but I'm still verifying the outputs and fixing the regressions with other tests. I'll put something up soon as I'm done @mosyp @xianwill

**Comment by alamb** [comment]
Marking PRs that are over a month old as stale -- please let us know if there is additional work planned or if we should close them.

**Comment by alamb** [comment]
I merged this branch to master and with the fix from https://github.com/apache/arrow-rs/pull/1166 from @helgikrs  this test now passes 🎉 

```
warning: `parquet` (test "array_struct_bug") generated 8 warnings
    Finished test [unoptimized + debuginfo] target(s) in 9.62s
     Running tests/array_struct_bug.rs (/Users/alamb/Software/df-target/debug/deps/array_struct_bug-ffc075f6b2fe1ef0)

running 1 test
test array_struct_bug ... ok
```

Thanks again for the report @mosyp

**Pull request closed without merging**
