### PR TITLE
Support Duration in JSON Reader

### PR DESCRIPTION
**Pull request by simonvandel**
# Which issue does this PR close?

Closes #.

# Rationale for this change
 

# What changes are included in this PR?

Add support for deserializing durations.

# Are there any user-facing changes?
Support for Duration in JSON deserialization.

### CODE REVIEW

**Comment by simonvandel** [comment]
Yes, the current PR only supports durations encoded as integers ot strings parsed as integers.

I think it's a good idea to explore if we should support other duration representations.

Do you think the current PR can be merged as-is? We can then create a follow-up issue to discuss the other representations.

**Comment by tustvold** [comment]
> Do you think the current PR can be merged as-is

I don't think we should merge this if it isn't consistent with other implementations

**Comment by simonvandel** [comment]
I tried pyarrow here: https://gist.github.com/simonvandel/ff420a412cc9a34d95a23086ecec3b15 using `uv run python hello.py`

It seems like duration is not supported:
```
pyarrow.lib.ArrowNotImplementedError: JSON conversion to duration[s] is not supported
```

**Review by alamb — APPROVED** [review]
I think this is a reasonable change to me -- thank you @simonvandel and @tustvold

**Pull request merged**
