### PR TITLE
Add `try_filter_leaves` to propagate error from filter closure

### LINKED ISSUE #5574: Make `filter` in `filter_leaves` API propagate error
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently `filter_leaves` API takes a closure which returns a `bool`. In some cases, e.g., https://github.com/apache/iceberg-rust/pull/245#discussion_r1545181844, we may like to propagate error from it.

**Describe the solution you'd like**

Changing the `filter` in `filter_leaves` to return `Result<bool>`.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #5574.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
Perhaps we could add a try_filter_leaves to avoid this being a breaking change, filter_leaves could just call this with unwrap

**Comment by viirya** [comment]
> Perhaps we could add a try_filter_leaves to avoid this being a breaking change, filter_leaves could just call this with unwrap

Sounds good to me. Let me update this later.

**Review by alamb — APPROVED** [review]
Makes sense to me. Thank you @viirya and @tustvold

**Comment by viirya** [comment]
Thank you @tustvold @alamb

**Pull request merged**
