### PR TITLE
Rename the `string` kernel to `concat_elements`.

### LINKED ISSUE #1747: Rename the `string` kernel to `concatenate_elements`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This is a follow-up of #1720.
We have added `concatenate by elements` support for string array and put it into the new created `string` kernel.
I suggest we should rename the kernel `concatenate_elements`.

There are some reasons I thought why `concatenate_elements` is better than `string`:
1. The name of the compute kernel should express what kind of operation will be done on an array, such as `cast`, `aggregate` ...
2. We can support the `concatenate_elements` operation on binary array, list array and other nested types. So `string` is not an appropriate name.
3. In cudf (which is based on Arrow c++, and more GPU supported), there are similar kernels and we can refer to their names.: https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/src/lists/combine/concatenate_list_elements.cu
https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/src/lists/combine/concatenate_rows.cu

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

Closes #1747.

# Rationale for this change
Please see the issue.

# Are there any user-facing changes?
Yes!

### CODE REVIEW

**Review by viirya — APPROVED** [review]

**Comment by alamb** [comment]
> Perhaps we should rename the function string_concat to concat_elements_string to be consistent with other modules?


This would be an excellent thing to do - I'll try and get it done later today

**Comment by alamb** [comment]
Or maybe just `concat_string` would enough 🤔

**Comment by alamb** [comment]
Proposed change in https://github.com/apache/arrow-rs/pull/1754

**Comment by HaoYang670** [comment]
Thank you for your review!

**Pull request merged**
