### PR TITLE
Add `async` into doc features

### LINKED ISSUE #1307: parquet async_writer not showing up in docs.rs parquet documentation
**Describe the bug**

The link to the `async_read` in the parquet 9.0.2 docs is not a link when published on docs.rs:

Screen Shot 2022-02-13 at 8 10 54 AM

**To Reproduce**
https://docs.rs/parquet/9.0.2/parquet/

**Expected behavior**
The link should be active.

**Additional context**
Came in via https://github.com/apache/arrow-rs/pull/1253

I think the issue may be that the `async` feature is not activated by default.

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

Closes #1307.
Closes https://github.com/apache/arrow-rs/issues/1617

# Rationale for this change
 
 

# What changes are included in this PR?
Add `async` to default enabled features, so that the link `arrow::async_reader` is active.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
THank you @HaoYang670 

Changing the default features of the arrow crate may have some non trivial downstream consequences for users of arrow.

What would you think about just updating the metadata for the docs.rs build following https://docs.rs/about/metadata? Perhaps something like:

```yml
[package.metadata.docs.rs]

# Whether to pass `--all-features` to Cargo (default: false)
all-features = true
```

?

**Comment by HaoYang670** [comment]
Thank you for your review! I will update my PR.

**Comment by HaoYang670** [comment]
Neither `all_features = true` nor `features = ["default", "async"]` works on my desktop.

**Comment by alamb** [comment]
> Neither all_features = true nor features = ["default", "async"] works on my desktop.

Can you share what you tried? Perhaps the output of `git diff` ?

**Comment by HaoYang670** [comment]
> > Neither all_features = true nor features = ["default", "async"] works on my desktop.
> 
> Can you share what you tried? Perhaps the output of `git diff` ?

I add
```
[package.metadata.docs.rs]
all_features = true
```
in parquet/Cargo.toml.

**Comment by alamb** [comment]
🤔 I haven't had a chance to really test, but it looks like docs.rs has some specific build process (that isn't just `cargo doc`) https://docs.rs/about/builds

**Comment by alamb** [comment]
Thanks @HaoYang670  -- I am trying to test this change using a local docs.rs build -- https://github.com/rust-lang/docs.rs/blob/master/README.md#build-subcommand 

WIll report how it goes.

**Comment by alamb** [comment]
I wasn't able to get the local docs.rs build to work and then ran out of time ;( Hopefully we'll get this into the next arrow release (it missed the cutoff for 10.0.0 sadly)

**Comment by HaoYang670** [comment]
> I wasn't able to get the local docs.rs build to work and then ran out of time ;( Hopefully we'll get this into the next arrow release (it missed the cutoff for 10.0.0 sadly)

Thanks a lot @alamb

**Comment by alamb** [comment]
FWIW I have tried several times to build docs.rs on my laptop and have not had any luck for some reason.

**Comment by alamb** [comment]
I am wary of merging this in without testing it as it might cause the docs.rs build to fail 😭

**Comment by alamb** [comment]
Marking as draft until we sort out testing

**Comment by alamb** [comment]
Thanks again @HaoYang670  for giving it a try.

**Comment by alamb** [comment]
🤔  I can't figure out the documentation build for dev

**Comment by alamb** [comment]
I published old versions here:

will watch doc builds

https://crates.io/crates/arrow/0.18.0
https://crates.io/crates/parquet/0.18.0

**Comment by alamb** [comment]
Glad I tested: https://docs.rs/crate/parquet/0.18.0 seems to have failed -- https://docs.rs/crate/parquet/0.18.0/builds/557342

```
[INFO] [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
[INFO] [stdout] c7db694a1e0ec0a7df60f4774a81f3d15861a69233e9177971982b83d9da03dd
[INFO] running `Command { std: "docker" "start" "-a" "c7db694a1e0ec0a7df60f4774a81f3d15861a69233e9177971982b83d9da03dd", kill_on_drop: false }`
[INFO] [stderr]  Documenting parquet v0.18.0 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0658]: `#[doc(cfg)]` is experimental
[INFO] [stderr]    --> src/arrow/mod.rs:124:21
[INFO] [stderr]     |
[INFO] [stderr] 124 | #[cfg_attr(doc_cfg, doc(cfg(feature = "async")))]
[INFO] [stderr]     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr]     |
[INFO] [stderr]     = note: see issue #43781 <https://github.com/rust-lang/rust/issues/43781> for more information
[INFO] [stderr]     = help: add `#![feature(doc_cfg)]` to the crate attributes to enable
[INFO] [stderr] 
[INFO] [stderr] error: Compilation failed, aborting rustdoc
[INFO] [stderr] 
[INFO] [stderr] For more information about this error, try `rustc --explain E0658`.
[INFO] [stderr] error: could not document `parquet`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name parquet src/lib.rs --target x86_64-unknown-linux-gnu -o /opt/rustwide/target/x86_64-unknown-linux-gnu/doc --cfg 'feature="arrow"' --cfg 'feature="async"' --cfg 'feature="base64"' --cfg 'feature="brotli"' --cfg 'feature="clap"' --cfg 'feature="cli"' --cfg 'feature="default"' --cfg 'feature="experimental"' --cfg 'feature="flate2"' --cfg 'feature="futures"' --cfg 'feature="lz4"' --cfg 'feature="serde_json"' --cfg 'feature="snap"' --cfg 'feature="test_common"' --cfg 'feature="tokio"' --cfg 'feature="zstd"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=78f9c9e2e62425b8 -L 
...
```

Looking into that

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-rs/issues/1695 to track this issue and will provide updates there

**Comment by HaoYang670** [comment]
Great work @alamb !

**Pull request merged**
