### PR TITLE
To pyarrow with schema

### LINKED ISSUE #3136: arrow to and from pyarrow conversion results in changes in schema
**Describe the bug**

Converting a RecordBatch to pyarrow RecordBatch and converting it back to rust RecordBatch results in inconsistent schema. 

**To Reproduce**

```
#[pyfunction]
fn lookup(py: Python<'_>, keys: PyObject) -> PyResult<PyObject> {
    // Input is Arrow RecordBatch
    let keys = RecordBatch::from_pyarrow(keys.as_ref(py))?;
    println!("keys: {:?}", keys);
    keys.to_pyarrow(py)
}

#[test]
    fn test_conversion() {
        let a: ArrayRef = Arc::new(Int32Array::from(vec![1, 2]));
        let b: ArrayRef = Arc::new(StringArray::from(vec!["a", "b"]));
        let input = RecordBatch::try_from_iter(vec![("a", a), ("b", b)]).unwrap();
        println!("input: {:?}", input);

        let res = pyo3::Python::with_gil(|py| {
            let x = lookup(py, input.to_pyarrow(py).unwrap()).unwrap();
            RecordBatch::from_pyarrow(x.as_ref(py)).unwrap()
        });

       assert_eq!(input, res);
}
       
```

output - 

```
input: RecordBatch { schema: Schema { fields: [Field { name: "a", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: None }, Field { name: "b", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, columns: [PrimitiveArray<Int32>
[
  1,
  2,
], StringArray
[
  "a",
  "b",
]], row_count: 2 }

keys: RecordBatch { schema: Schema { fields: [Field { name: "a", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }, Field { name: "b", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }], metadata: {} }, columns: [PrimitiveArray<Int32>
[
  1,
  2,
], StringArray
[
  "a",
  "b",
]], row_count: 2 }
```

`nullable: false` is what is different b/w the types.

**Expected behavior**

**Additional context**

Versions of the packages used - 

```
arrow = { version = "25.0.0", features = ["pyarrow"] }
pyo3 = { version = "0.17.1" }
```

### PR DESCRIPTION
**Pull request by doki23**
closes #3136

### CODE REVIEW

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
Is this test actually run in CI? I can't see it in the output?

**Comment by doki23** [comment]
Yes, seems something went wrong

**Comment by tustvold** [comment]
I don't think the CI is configured to run tests with the pyarrow feature enabled?

**Comment by doki23** [comment]
Great! 👍🏻

**Comment by tustvold** [comment]
Thank you :+1:

**Pull request merged**
