### PR TITLE
add support for date and timestamp prior to 1/1/1970

### PR DESCRIPTION
**Pull request by amitagrawalcs**
# Rationale for this change
 
When we read date prior to 1st-Jan-1970 using parquet module, code panic by saying 'No such local time'. This bug exists because datatype date and timestamp in enum 'Field' (parquet/src/record/api.rs) is u32 and u64 which indicates the number of days from EPOCH DATE. In case of date being prior to 1/1/1970, number of days will be a negative integer that can't be hold by u32 and u64.

# What changes are included in this PR?

Datatype of date and timestamp in Field enum is changed from u32 and u64 to i32 and i64 respectively.

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by liukun4515** [comment]
Thanks for your contributions. @amitagrawalcs 
Can you add some tests for this fix?

**Comment by alamb** [comment]
Also note the Integration test failure is fixed on master, so when you rebase or merge the next run should work

**Comment by alamb** [comment]
Hi @amitagrawalcs  -- we are preparing for an arrow release this week -- will you have a chance to add some tests to this PR?

**Comment by alamb** [comment]
Marking as draft until tests are added. Please mark as ready to review when it is next ready 

Thanks!

**Comment by tustvold** [comment]
This PR has been inactive for a while so closing to clear the backlog, please feel free to reopen if you come back to this

**Comment by tustvold** [comment]
It might also have been fixed by https://github.com/apache/arrow-rs/pull/3437

**Pull request closed without merging**
