### PR TITLE
Parquet: omit min/max for interval columns when writing stats

### LINKED ISSUE #5145: Parquet: Interval columns shouldn't write min/max stats
**Describe the bug**

See parquet spec:

> The sort order used for `INTERVAL` is undefined. When writing data, no min/max statistics should be saved for this type and if such non-compliant statistics are found during reading, they must be ignored.

- https://github.com/apache/parquet-format/blob/066f9817332da32bdc6dc6dea833b6ee9c269934/LogicalTypes.md?plain=1#L537-L539

**To Reproduce**

Test in https://github.com/apache/arrow-rs/blob/ef6932f31e243d8545e097569653c8d3f1365b4d/parquet/src/column/writer/mod.rs:

```rust
    #[test]
    fn test_interval_should_not_have_min_max() {
        let input = [
            vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
            vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
        ]
        .into_iter()
        .map(|s| ByteArray::from(s).into())
        .collect::<Vec<_>>();

        let page_writer = get_test_page_writer();
        let mut writer = get_test_interval_column_writer(page_writer);
        writer.write_batch(&input, None, None).unwrap();

        let metadata = writer.close().unwrap().metadata;
        let stats = if let Some(Statistics::FixedLenByteArray(stats)) = metadata.statistics() {
            stats.clone()
        } else {
            panic!("metadata missing statistics");
        };
        assert!(!stats.has_min_max_set());
    }

    fn get_test_interval_column_writer(
        page_writer: Box<dyn PageWriter>,
    ) -> ColumnWriterImpl<'static, FixedLenByteArrayType> {
        let descr = Arc::new(get_test_interval_column_descr());
        let column_writer = get_column_writer(descr, Default::default(), page_writer);
        get_typed_column_writer::<FixedLenByteArrayType>(column_writer)
    }

    fn get_test_interval_column_descr() -> ColumnDescriptor {
        let path = ColumnPath::from("col");
        let tpe =
            SchemaType::primitive_type_builder("col", FixedLenByteArrayType::get_physical_type())
                .with_length(12)
                .with_converted_type(ConvertedType::INTERVAL)
                .build()
                .unwrap();
        ColumnDescriptor::new(Arc::new(tpe), 0, 0, path)
    }
```

**Expected behavior**

Should pass test. Currently fails as seems min/max is being set.

**Additional context**

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5145

# Rationale for this change
 

# What changes are included in this PR?

Add extra checks before calculating min/max for chunks/pages, to ignore Interval columns

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
Makes sense to me

**Comment by tustvold** [comment]
What ColumnOrder are we currently writing for these columns?

**Comment by Jefffrey** [comment]
I noticed this:

https://github.com/apache/arrow-rs/blob/6d4b8bbad95c7e4fec0c4f1fb755ad7a1c542983/parquet/src/file/writer.rs#L333

- Unsure if there are other places to consider

Looks like might be a separate issue, to implement writing ColumnOrder

**Comment by Jefffrey** [comment]
Raised https://github.com/apache/arrow-rs/issues/5152 for the column order issue

**Pull request merged**
