### PR TITLE
MINOR: Fix clippy error after updating rust toolchain

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

There are a few clippy errors on CI (e.g. https://github.com/apache/arrow-rs/runs/7140900792?check_suite_focus=true). I can reproduce it once do `rustup update` locally. 

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao @tustvold

**Review by HaoYang670 — APPROVED** [review]
LGTM! 
I have no right to merge this. We need an approval from a maintainer.

**Comment by viirya** [comment]
cc @alamb too

**Review by liukun4515 — APPROVED** [review]
Thanks @viirya

**Comment by viirya** [comment]
Thank you @liukun4515 @HaoYang670

**Pull request merged**
