### PR TITLE
Use Arc<str> inside Field (#3955)

### PR DESCRIPTION
**Pull request by tustvold**
_Draft as I am not sure about this and needs some shenanigans to work for serde_

# Which issue does this PR close?

Part of #3955

# Rationale for this change
 

Allows for cheaper cloning of DataType and potentially faster comparisons, by comparing pointers instead of string contents

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
I think if we Arc the entire Field -- as in https://github.com/apache/arrow-rs/pull/3965 we may not need this

I know that @crepererum  has mentioned other downstream places that copy the field name (like Statistics in DataFusion) but I think maybe a better design would be to update those downstream uses to hold a `FieldRef` rather than just the name 🤔

**Comment by crepererum** [comment]
> hold a `FieldRef` rather than just the name

That's not always possible, since you may not have the datatype at hand yet. So at least during logical planning in DF this ain't an option.

**Comment by alamb** [comment]
> That's not always possible, since you may not have the datatype at hand yet. So at least during logical planning in DF this ain't an option.

🤔  I think as soon as DataFusion creates a `LogicalPlan` / `Expr` it is possible to get the type using https://docs.rs/datafusion/latest/datafusion/prelude/enum.Expr.html#impl-ExprSchemable-for-Expr

Or more to the point, with a LogicalPlan you also have a `Schema` with `Field`

**Comment by tustvold** [comment]
Going to close this for now to clear up the review backlog slightly

**Pull request closed without merging**
