### PR TITLE
Add `Decimal128` to `DataType::is_numeric` and clean the numeric casting code

### LINKED ISSUE #2611: `DataType::is_numeric` should match the `is_numeric` function in Datafusion.
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In datafusion, we have:
```rust
/// Determine if a DataType is signed numeric or not
pub fn is_signed_numeric(dt: &DataType) -> bool {
    matches!(
        dt,
        DataType::Int8
            | DataType::Int16
            | DataType::Int32
            | DataType::Int64
            | DataType::Float16
            | DataType::Float32
            | DataType::Float64
            | DataType::Decimal128(_, _)
    )
}

/// Determine if a DataType is numeric or not
pub fn is_numeric(dt: &DataType) -> bool {
    is_signed_numeric(dt)
        || matches!(
            dt,
            DataType::UInt8 | DataType::UInt16 | DataType::UInt32 | DataType::UInt64
        )
}
```

We should update `DataType::is_numeric` to contain these constructors so that we could remove the redundant `is_numeric` in datafusion (https://github.com/apache/arrow-datafusion/issues/1613)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by HaoYang670**
# Which issue does this PR close?

Closes #2611.

# Rationale for this change
 

We try to match the `is_numeric` function in the Datafusion (aka, adding Float16 and Decimal128). However, as `Float16` is not supported by some upstream libraries (such as lexical_core::FromLexical), we can't add it now. (This is not a big deal because Float16 is a minor use case). Decimal128 could be added successfully.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — COMMENTED** [review]
I'm not totally sure about this, as I'm not entirely sure how these methods are being used. But Decimal is distinct from Float32, Int16, etc... in that it isn't a PrimitiveArray. I'm not sure if this is or isn't an issue

**Comment by HaoYang670** [comment]
Unfortunately, I don't find a definition of which types are numeric in the Arrow format: https://github.com/apache/arrow/blob/master/format/Schema.fbs

We have a trait `ArrowNumbericType` in arrow-rs, but there is no doc to describe what is it and why we need it. 

In datafusion, the definition of `is_numeric` is here: https://github.com/apache/arrow-datafusion/blob/master/datafusion/expr/src/binary_rule.rs#L392-L414. It covers the types in `DataType::is_numeric` and `Float16` and `Decimal128`.

This PR is trying to build a consistent definition of `DataType::is_numeric` and `is_numeric` in the Datafusion, so that we could remove the `is_numeric` in Datafusion and users will not get confused when choosing between the two.

**Comment by tustvold** [comment]
> so that we could remove the is_numeric in Datafusion

In the context of DataFusion what is it used to determine?

**Comment by HaoYang670** [comment]
The only use case currently is the numerical coercion (https://github.com/apache/arrow-datafusion/blob/master/datafusion/expr/src/binary_rule.rs#L570, and https://github.com/apache/arrow-datafusion/blob/master/datafusion/expr/src/binary_rule.rs#L187)

**Comment by liukun4515** [comment]
> > so that we could remove the is_numeric in Datafusion
> 
> In the context of DataFusion what is it used to determine?

Datafusion and arrow-rs are two different system, in the datafusion some cases or operations are not supported now, but that operations maybe supported in the arrow-rs.

We just can consider the arrow-rs, and make the consistent in the arrow-rs. 
@HaoYang670 @tustvold

**Comment by HaoYang670** [comment]
> Datafusion and arrow-rs are two different system, in the datafusion some cases or operations are not supported now, but that operations maybe supported in the arrow-rs.

Thank you, @liukun4515. At least, I think we should rename the `is_numeric` in the Datafusion, so that developers would not misuse the two functions.

**Comment by kmitchener** [comment]
FWIW, I think this PR is correct and it would be nice to get in the next release. DataFusion should depend on these functions and remove it's own similarly-named functions. I'd be happy to do a follow-on issue for DF to clean that up. 

In DF, these functions are only used for determining type to type coercion rules, but then it uses arrow-rs's cast functions to do the actual conversion .. shouldn't the coercion rules also be in arrow-rs which also manages the types, the type implementations, and the casting? There's a can_cast_types() which is either what we need already, or a similar function like can_cast_types_without_loss().

**Comment by tustvold** [comment]
I think my major reservation with this as it stands is that at least currently the decimal support in arrow-rs is extremely limited, I think once we have all the operations for decimals as other "numerics" I would be more happy with this change. Otherwise I think it is confusing to label decimals as numeric types, when they aren't properly supported

**Comment by alamb** [comment]
What ever happed with this PR?

**Comment by alamb** [comment]
Converting to draft until we decide on next steps

**Comment by tustvold** [comment]
Closed by https://github.com/apache/arrow-rs/pull/3121

**Pull request closed without merging**
