### PR TITLE
Disallow cast from other datatypes to NullType

### LINKED ISSUE #1923: Disallow cast from other datatypes to NullType
**Describe the bug**

We allow casting from other datatypes to NullType (see `can_cast_types`). I suspect that this is a mistake.

For example, Spark doesn't allow casting from any datatypes to NullType.

I also checked C++ Cast kernels. Mostly the datatypes cannot cast to NullType (e.g. https://github.com/apache/arrow/blob/53752adc6b81166cd4ee7db5a819494042f29197/cpp/src/arrow/compute/kernels/scalar_cast_test.cc#L187-L211). I said "mostly" because I don't see explicit tests for other cases like Decimal, but I suspect that it is not allowed but just lack of test coverage.

I don't see there is cast kernel in C++ for casting to NullType except for a special case (`dict<null> -> null`): https://github.com/apache/arrow/blob/53752adc6b81166cd4ee7db5a819494042f29197/cpp/src/arrow/compute/kernels/scalar_cast_numeric.cc#L748-L751. Even for that, there is a comment questioning about it.

**To Reproduce**

**Expected behavior**

Cast kernel should not allow casting from any datatypes to NullType.

**Additional context**

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #1923 

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by liukun4515** [comment]
@alamb Does this may break some usages in the datafusion or influxio? I have not checked it.

**Comment by liukun4515** [comment]
@nevi-me @viirya PTAL

**Comment by alamb** [comment]
>  @alamb Does this may break some usages in the datafusion or influxio? I have not checked it.

I will check

**Review by alamb — APPROVED** [review]
LGTM, and thanks again to @viirya  for sorting this out downstream in datafusion: https://github.com/apache/arrow-datafusion/pull/2794

**Pull request merged**
