### PR TITLE
doc: deploy crate docs to GitHub pages

### PR DESCRIPTION
**Pull request by xxchan**
# Which issue does this PR close?

Closes #.

# Rationale for this change

arrow-rs has so many crates. We often need to browse the doc for more than one crates. But on doc.rs, we can't go to other crates conveniently.

image

Deploying to GitHub pages can improve the situation

image

See it on my fork: https://xxchan.github.io/arrow-rs

https://github.com/xxchan/arrow-rs/actions/workflows/docs.yml 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
Another strategy that is used for other arrow projects is to publish the apache site (e.g. https://arrow.apache.org/datafusion/)

This is described in https://github.com/apache/arrow-datafusion/tree/main/docs#release-process

I would be happy to help figure out how to make the process work here as well

**Comment by alamb** [comment]
Thank you @xxchan  -- this is very helpful.

**Review by tustvold — APPROVED** [review]

**Comment by alamb** [comment]
Let's merge this and see how it works

**Comment by xxchan** [comment]
Maybe we need to update asf.yaml

**Comment by alamb** [comment]
Yes, I think we need to do the same thing as in DataFusion

@xxchan would it be possible for you to look into doing so? Aka what is described in https://github.com/apache/arrow-rs/pull/4436#issuecomment-1598815865?

If you don't have time that is also fine, I can revert this change and we can work on it when we do have time

**Comment by xxchan** [comment]
There is a ASF INFRA doc, but I have no access to the wiki
https://infra.apache.org/github-pages.html

**Comment by alamb** [comment]
@martin-g  did the work in DataFusion via https://github.com/apache/arrow-datafusion/pull/5670 -- maybe that is enough?

**Pull request merged**
