### PR TITLE
Fix generate_decimal128_case in integration test

### LINKED ISSUE #1439: Fix generate_decimal128_case in integration test
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

This ticket is for `generate_decimal128_case` case in integration test.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
See #1404

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1439.

# Rationale for this change
 
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by liukun4515 — APPROVED** [review]
Thanks @viirya

**Comment by viirya** [comment]
Thanks @liukun4515 !

**Review by alamb — APPROVED** [review]
Looks good to me -- thanks @viirya

**Comment by viirya** [comment]
Thanks @alamb ! I will continue fixing other integration test failures.

**Pull request merged**
