### PR TITLE
Additional gcp authentication

### LINKED ISSUE #3490: Support GCP Workload Identity
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the object_store crate only supports obtaining credentials using a provided service account, it would be beneficial if it could also optionally obtain credentials from its environment. This would be consistent with the behaviour of the aws and azure implementations, and avoids requiring users to handle sensitive long-term service account credentials.

**Describe the solution you'd like**

If no service account is specified, it should fallback to trying to get credentials from a metadata endpoint. 

This is documented [here](https://cloud.google.com/docs/authentication/get-id-token#metadata-server)

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by winding-lines**
# Which issue does this PR close?

Closes #3490 .

# Rationale for this change
 

# What changes are included in this PR?

I am requesting guidance on this PR. It adds the `gap_auth` crate for additional authentication mechanisms on GCP. This could replace the existing service account code, I wasn't sure which way you want to go.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
We generally have tried to keep the dependency tree down, especially as this leads to a more consistent experience. I would prefer we just implement workload identity in crate, it should be relatively straightforward

**Comment by winding-lines** [comment]
@tustvold thanks for the fast reply :) My main interest is to implement `application_default_credentials`, this is coming transitively from the work I do on `polars` project. Are you okay if I take a pass at implementing both workload identity and application credentials in this PR?

**Comment by tustvold** [comment]
SGTM, perhaps we should close this and you can open a new one with those changes once they're ready (will help me know when to review  😅)

**Comment by winding-lines** [comment]
Ok great, this is a big relief because I really need that specific authentication. The way the GitHub issue is written it definitely covers both cases so I would leave the issue management to you. 🤗

**Pull request closed without merging**
