### PR TITLE
Always validate the array data (except the `Decimal`) when creating array in IPC reader

### LINKED ISSUE #2541: Always validate the array data when creating array in IPC reader
IMO we should probably be validating all of them, I'm not sure why we aren't validating some of them... IPC is inherently not trusted

_Originally posted by @tustvold in https://github.com/apache/arrow-rs/pull/2525#discussion_r950697745_

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

Closes #2541.

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by HaoYang670** [comment]
5 tests failures so far
```
failures:

---- ipc::reader::tests::read_generated_streams_014 stdout ----
thread 'ipc::reader::tests::read_generated_streams_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("-11697 is too small to store in a Decimal128 of precision 3. Min is -999")', arrow/src/ipc/reader.rs:497:18

---- ipc::reader::tests::read_generated_files_014 stdout ----
thread 'ipc::reader::tests::read_generated_files_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("-11697 is too small to store in a Decimal128 of precision 3. Min is -999")', arrow/src/ipc/reader.rs:497:18

---- json::reader::tests::test_row_type_validation stdout ----
thread 'json::reader::tests::test_row_type_validation' panicked at 'assertion failed: `(left == right)`
  left: `"Json error: Expected JSON record to be an object, found Array([Number(1), String(\"hello\")])"`,
 right: `"Json error: Expected JSON record to be an object, found Array [Number(1), String(\"hello\")]"`', arrow/src/json/reader.rs:2624:9

---- ipc::writer::tests::read_and_rewrite_generated_streams_014 stdout ----
thread 'ipc::writer::tests::read_and_rewrite_generated_streams_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("-11697 is too small to store in a Decimal128 of precision 3. Min is -999")', arrow/src/ipc/reader.rs:497:18

---- ipc::writer::tests::read_and_rewrite_generated_files_014 stdout ----
thread 'ipc::writer::tests::read_and_rewrite_generated_files_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("-11697 is too small to store in a Decimal128 of precision 3. Min is -999")', arrow/src/ipc/reader.rs:497:18
```

**Comment by viirya** [comment]
`test_row_type_validation` passes in current master. You can retry after `cargo clean`.

**Comment by viirya** [comment]
For the following tests, there are some out of range decimal values for the given precision in older version of generated files. A known issue.

```
---- ipc::reader::tests::read_generated_streams_014 stdout ----
thread 'ipc::reader::tests::read_generated_streams_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("-11697 is too small to store in a Decimal128 of precision 3. Min is -999")', arrow/src/ipc/reader.rs:497:18

---- ipc::reader::tests::read_generated_files_014 stdout ----
thread 'ipc::reader::tests::read_generated_files_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("-11697 is too small to store in a Decimal128 of precision 3. Min is -999")', arrow/src/ipc/reader.rs:497:18
```

**Comment by HaoYang670** [comment]
> A known issue.

Is there any ticket to track this?

**Comment by viirya** [comment]
> > A known issue.
> 
> Is there any ticket to track this?

I'd opened a ticket before to know why there are these values: https://issues.apache.org/jira/browse/ARROW-16696

BTW, I said "a known issue", not meaning it is some bug needed to fix. Just a known topic/problem if you try to validate these decimal values from the generated files.

**Comment by liukun4515** [comment]
why the data in the ipc can't be trusted from this issue https://github.com/apache/arrow-rs/issues/2541 ? @HaoYang670 @tustvold

**Comment by tustvold** [comment]
The IPC APIs are safe, it therefore cannot be possible to create UB using them. Currently reading a file with invalid list offsets, for example, will result in UB

**Comment by HaoYang670** [comment]
At least, we should make the implementation consistent.
So far, Utf8 / Binary arrays use checked build function, however other arrays use `build_unchecked`.

It is weird for me that in `create_primitative_array` some arrays are checked, but others are not. If there are some reasons, we should doc them.

**Comment by tustvold** [comment]
Regarding the Decimal validation there is an open ticket regarding how we handle this #2387 

Perhaps we could back out the change to validating DecimalArray with a TODO tied to that ticket, and get the rest of this PR in?

**Comment by HaoYang670** [comment]
> Regarding the Decimal validation there is an open ticket regarding how we handle this #2387
> 
> Perhaps we could back out the change to validating DecimalArray with a TODO tied to that ticket, and get the rest of this PR in?

Sounds great. I will update the code and add more docs.

**Review by tustvold — APPROVED** [review]

**Pull request merged**
