### PR TITLE
FixedSizeBinaryArray::try_from_sparse_iter failed when given all Nones

### LINKED ISSUE #1390: `FixedSizeBinaryArray::try_from_sparse_iter` failed when given all Nones
**Describe the bug**

try_from_sparse_iter expects at least one item to have Some to determine the size. This is a bad assumption as it may recieve all Nones. 

```
InvalidArgumentError("column types must match schema types, expected FixedSizeBinary(32) but found FixedSizeBinary(0) at column index 0"
```
**To Reproduce**

```
        let none_option: Option<[u8; 32]> = None;
        let item = arrow::array::FixedSizeBinaryArray::try_from_sparse_iter(
            vec![none_option, none_option, none_option].into_iter(),
        )
        .unwrap();
       let rb = arrow::record_batch::RecordBatch::try_new(
            arrow_schema.clone(),
            vec![std::sync::Arc::new(item)],
        )
        .unwrap();

```

**Expected behavior**

A record batch with a colum of all nulls.

**Additional context**

I would suggest fixing it by changing the behaviour of defaulting in **array_binary.rs:560**

```
let size = size.unwrap_or(0);
```

or changing the schema validation to handle a 0 size if the array is empty.

### PR DESCRIPTION
**Pull request by jamescorbett**
# Which issue does this PR close?

Closes ##1390.

# Rationale for this change
 
Minimally invasive change to work around Options being unsized if None.

# What changes are included in this PR?

Adding new function to get access to default size while maintaining original functionality.

# Are there any user-facing changes?

One additional function `try_from_sparse_iter_sized`

### CODE REVIEW

**Review by viirya — COMMENTED** [review]
Thanks for the fix. Can you also add a test for the fix?

**Comment by alamb** [comment]
I agree we should have a test prior to merging. Thanks @jamescorbett

**Comment by alamb** [comment]
We can probably just copy the test from https://github.com/apache/arrow-rs/issues/1390

**Comment by jamescorbett** [comment]
I will do sorry I have had work commitments.

**Comment by alamb** [comment]
>  I will do sorry I have had work commitments.


No worries -- sorry I didn't mean to pressure you. Thank you for the contribution; I can add the tests too if you don't have time

**Comment by alamb** [comment]
Marking as a draft to signify there is still some work to do. Please feel free to mark it ready for review when it is

**Comment by tustvold** [comment]
Closing this as https://github.com/apache/arrow-rs/pull/3054 has added support for this

**Pull request closed without merging**
