### PR TITLE
Expose use_emulator option for GCS

### LINKED ISSUE #2627: Expose option to use GCS object store in integration tests
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

When running integration tests is is useful to be able to work against emulated services. As such it would be great to publicly expose an option to configure the GCS backend in object store for use with fake-gcs.

**Describe the solution you'd like**

Expose an option on GoogleBuilder to configure use with fake-gcs.

**Describe alternatives you've considered**

Not doing it.

**Additional context**

### PR DESCRIPTION
**Pull request by roeap**
# Which issue does this PR close?

Closes #2627

# Rationale for this change
 
Currently a test-only option is exposed, to configure an unsafe client. To avoid exposing third party types in the public API, I moved the same logic as used in test behind a `use_emulator` option. 

Also after some trials around copy-if-not exists, it seemed to me fake-gcs so far does not support this. fsouza/fake-gcs-server#909.

# What changes are included in this PR?

New builder option for GCS object sore.

# Are there any user-facing changes?

yes

### CODE REVIEW

**Comment by tustvold** [comment]
I wonder if we should instead be configuring fake-gcs to use HTTP, we could then provide an `with_allow_http` like the we do for S3 🤔

I'll have a quick play

**Comment by roeap** [comment]
This is likely much better - consistent and infallible 😀.

**Comment by tustvold** [comment]
I switched away from using insecure TLS in https://github.com/apache/arrow-rs/pull/2632 PTAL

**Comment by roeap** [comment]
From my perspective, your approach using http is superior, so going that way makes more sense. Given the need is only to do integration test "somehow"...

**Comment by tustvold** [comment]
Ok let's move forward with that then

**Pull request closed without merging**
