### PR TITLE
fix: Scalar math operations on slices

### LINKED ISSUE #742: Arithmetic with scalars doesn't work on slices
**Describe the bug**

As in #738 and #740, `modulus_scalar` and `divide_scalar` don't work on slices.

**To Reproduce**

```
    #[test]
    fn test_primitive_array_modulus_scalar_sliced() {
        let a = Int32Array::from(vec![Some(15), None, Some(9), Some(8), None]);
        let a = a.slice(1, 4);
        let a = as_primitive_array(&a);
        let actual = modulus_scalar(a, 3).unwrap();
        let expected = Int32Array::from(vec![None, Some(0), Some(2), None]);
        assert_eq!(actual, expected);
    }
```

**Expected behavior**
The test succeeds.

**Actual behavior**
The test doesn't succeed.

**Additional context**

### PR DESCRIPTION
**Pull request by bjchambers**
# Which issue does this PR close?

Closes #742.

# Rationale for this change
 
# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by bjchambers** [comment]
This depends on #739.

**Comment by jhorstmann** [comment]
CI for SIMD is failing because the import for the `unary` function is behind the non-simd feature, it wasn't used before and so avoided an unused import warning:

```
#[cfg(not(feature = "simd"))]
use crate::compute::kernels::arity::unary;
```

Otherwise this looks good to me.

**Comment by bjchambers** [comment]
> CI for SIMD is failing because the import for the `unary` function is behind the non-simd feature, it wasn't used before and so avoided an unused import warning:
> 
> ```
> #[cfg(not(feature = "simd"))]
> use crate::compute::kernels::arity::unary;
> ```
> 
> Otherwise this looks good to me.

Thanks! I hadn't gotten around to looking at the failure. Posted an update that removes the conditional.

**Review by alamb — APPROVED** [review]
Thank you @bjchambers

**Pull request merged**
