### PR TITLE
fix(object_store): only add encryption headers for SSE-C in get request

### PR DESCRIPTION
**Pull request by jiachengdb**
# Which issue does this PR close?

Follow up https://github.com/apache/arrow-rs/pull/6230.

# Rationale for this change
 

Make the previous PR safer.

# What changes are included in this PR?

In GET request, only include the encryption headers if it's SSE-C.

Checking https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax, the GET only expects headers for these. If it's using other encryptions like sse-kms or sse:kms:dsse, we don't need to attach the headers.

```
x-amz-server-side-encryption-customer-algorithm: SSECustomerAlgorithm
x-amz-server-side-encryption-customer-key: SSECustomerKey
x-amz-server-side-encryption-customer-key-MD5: SSECustomerKeyMD5
```

# Are there any user-facing changes?

### CODE REVIEW

**Comment by wjones127** [comment]
Yeah if you run the unit tests on main against AWS S3 with encryption on, the other encrpytion tests fail with:


```
thread 'aws::tests::s3_test_get_nonexistent_bucket' panicked at src/aws/mod.rs:503:9:
Generic S3 error: Client error with status 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>x-amz-server-side-encryption header is not supported for this operation.</Message><ArgumentName>x-amz-server-side-encryption</ArgumentName><ArgumentValue>aws:kms:dsse</ArgumentValue><RequestId>TBCZ37DGDBR7C1MV</RequestId><HostId>yfPR3yxVUaJiqXojttGjTiAlPJcnUImZQsoSwCCtJgFQGSbNRka+A+zpNzlXQ2MXSLvLImYvzao=</HostId></Error>
```

But after this PR, they pass again 👍 

**However**, I noticed one issue. You can see here we run tests against S3 serially here:

https://github.com/apache/arrow-rs/blob/e5d9816dfb7fc776732526acac3905fcb2764ef4/object_store/src/aws/mod.rs#L423-L441

But your `test_s3_ssec_encryption_with_minio` test runs in parallel. These tests interfere and often don't pass if you run the whole suite. **Could you also refactor to run serially just like the other encryption tests?**

**Comment by jiachengdb** [comment]
> Yeah if you run the unit tests on main against AWS S3 with encryption on, the other encrpytion tests fail with:

Is this against localstack, or real S3? How to reproduce this? Just run with `TEST_INTEGRATION=1` ?

**Comment by wjones127** [comment]
> > Yeah if you run the unit tests on main against AWS S3 with encryption on, the other encrpytion tests fail with:
> 
> Is this against localstack, or real S3? How to reproduce this? Just run with `TEST_INTEGRATION=1` ?

When I say "AWS S3" I mean "real S3" (the one run by AWS).

To run, just set the environment variables to point at S3. So don't set `AWS_ENDPOINT`. Use real AWS credentials. And run with `TEST_INTEGRATION=1` and the other variables that gate the encryption tests.

And to be clear, your PR is fine. I was saying `main` is failing, not this branch.

**Comment by jiachengdb** [comment]
It could be related to MinIO vs localstack differences too.

The signing() and tagging() tests are failing on the MinIO https endpoint: `AWS_ENDPOINT=https://localhost:9000`

**Comment by jiachengdb** [comment]
Maybe we can wait until localstack releases the SSE-C support in their latest docker, and converge the SSE-C test to run on localstack.

**Comment by jiachengdb** [comment]
I can take migrating the test to localstack.

**Comment by wjones127** [comment]
Alright, nevermind. Let's leave changing the tests for later once we can use localstack for everything.

**Review by wjones127 — APPROVED** [review]

**Pull request merged**
