### PR TITLE
Docstrings for Timestamp*Array.

### PR DESCRIPTION
**Pull request by novemberkilo**
# Which issue does this PR close?

Re #302 

@alamb thought I would add documentation for the `Timestamp*Array` types. Starting off with `TimestampSecondArray` to get some quick feedback. A couple of specific questions for you:
- There are no assertions here ... I am only trying to provide some hints on how to set these up. Is this ok?
- Curious about how to document things that are currently under the feature flag `chrono-tz` -- specifically, the ability to specify `Australia/Sydney` as the timezone. Is this appropriate and if so, shall I just make reference to the flag needing to be enabled?

Thankyou.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you @novemberkilo 

> There are no assertions here ... I am only trying to provide some hints on how to set these up. Is this ok?

I think it is ok, though adding some assertions as a way to illustrate how to access the values is valuable and common in Rust.

For example, perhaps you could add a call to `assert_eq!(arr.value_as_datetime(), "1969-08-25T09:34:49+0:00")` to show how it could be accessed, in addition to the comments

> Curious about how to document things that are currently under the feature flag chrono-tz -- specifically, the ability to specify Australia/Sydney as the timezone. Is this appropriate and if so, shall I just make reference to the flag needing to be enabled?

I think it is definitely cool to document things under feature flags with a note about what features are needed. 

Finally in terms of documenting `TimestampNanosecondArray`, `TimetampMillisecondArray`, etc, I recommend leaving a link to the examples on `TimestampSecondArray` with a note that the others work similarly rather than replicating the examples for each array

**Review by alamb — APPROVED** [review]
Looks good -- thank you @novemberkilo

**Comment by alamb** [comment]
@novemberkilo  this PR is still marked as a Draft. Do you think it is ready to merge or are there other things you plan to do?

**Comment by novemberkilo** [comment]
Ah sorry about that @alamb - now ready for review and merge. Thanks.

**Comment by alamb** [comment]
Thanks again @novemberkilo

**Pull request merged**
